---
title: |
  | SOC2069
  | Researching Social Life 1
subtitle: <br><br>Designing social research
author: <br><br><br> <b>Dr. Chris Moreh</b>
format: 
  revealjs:
    history: false
    #revealjs-plugins:
     # - ../my_plugins/countdown
     # - ../my_plugins/fullscreen
     # - ../my_plugins/elapsed
    title-slide-attributes:
      data-background-color: "white"
      data-background-iframe: "https://lab.hakim.se/particles/01/"
      data-background-interactive: true
      data-background-opacity: "0.2"
      data-background-size: 100vh
      data-transition: "slide-out"
      data-background-transition: "fade"
    controls: true
   #controls-layout: edges
    controls-back-arrows: faded
    slide-number: false
    preview-links: true
    theme: ../my_themes/cgm.scss
    logo:  "../pics/Res_Soc_Life_logo.png"
    incremental: true
    self-contained: true
bibliography: references.bib
csl: ../../american-sociological-association.csl
---

## Outline {background-iframe="https://lab.hakim.se/particles/01/" background-opacity="0.2" transition="slide"}

::: {.outlineslide .nonincremental}
1.  Information and data
2.  Interests and questions
3.  Casing and sampling
4.  Methods and ethics
:::

# Data: taming social information {background-iframe="https://lab.hakim.se/particles/01/" background-opacity="0.2" transition="slide-in fade-out"}

::: sectionhead
1 [2 3 4]{.opq}
:::

## Information

::: slidehead
1 [2 3 4]{.opq}
:::

-   the question of how to capture informatiion in an efficient way for sociological analysis

-   the 'map and the territory'' qoestion

. . .

> "Even if it were possible to observe people closely as their lives proceeded, we could not guarantee that this strategy would collect"truer" information, especially about such unobservable matters as motivations, perceptions, and views " [@gerson2020, pp.20?]

-   also the question of 'stories'; for this, see also @byrne2002

-   stories about cases, individual or 'variables'

-   

## Topic

## 3

-   thick description

-   'explanatory' rather than 'predictive analysis' (Gerson and damaske 2020; 14)[@gerson2020]

-   "what," "why," and "how" questions. - 'depth interviewing' that connect inductive approaches to theory

-   what can small samples tell us?

-   

## Sanpling 1

-   setting 'sample bundaries' depth interviewing)

-   

## Sampling 2

## Conc

[@goldthorpe2007; @hacking1990; @halsey2004, p. 23]

## References and further readings {background-color=#e3e5e8}
