<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HOME - Worksheet 8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../..//site_pics/SOC2069_logo_noaxis.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="../../site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet">
<link href="../../site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet">
<script src="../../site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="labcss.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">HOME</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../Structure.html" rel="" target="">
 <span class="menu-text">Module structure</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Materials/Labs/Worksheet_1.html" rel="" target="">
 <span class="menu-text">Week 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Materials/Labs/Worksheet_2.html" rel="" target="">
 <span class="menu-text">Week 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ttt" rel="" target="">
 <span class="menu-text">Week 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../Materials/Labs/Worksheet_4.html" rel="" target="" aria-current="page">
 <span class="menu-text">Week 4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Materials/Labs/Worksheet_5.html" rel="" target="">
 <span class="menu-text">Week 5</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ttt" rel="" target="">
 <span class="menu-text">Week 6</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ttt" rel="" target="">
 <span class="menu-text">Week 7</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ttt" rel="" target="">
 <span class="menu-text">Week 8</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ttt" rel="" target="">
 <span class="menu-text">Week 9</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ttt" rel="" target="">
 <span class="menu-text">Week 10</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ttt" rel="" target="">
 <span class="menu-text">Assessment</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://ncl.instructure.com/courses/53153" rel="" target=""><i class="bi bi-house-lock" role="img" aria-label="Canvas page (Newcastle University login required)">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#intro" id="toc-intro" class="nav-link active" data-scroll-target="#intro">Intro</a></li>
  <li><a href="#readings" id="toc-readings" class="nav-link" data-scroll-target="#readings">Readings</a></li>
  <li><a href="#exercise-0-setup" id="toc-exercise-0-setup" class="nav-link" data-scroll-target="#exercise-0-setup">Exercise 0: Setup</a></li>
  <li><a href="#exercise-1-the-effect-of-gender-on-subjective-wellbeing" id="toc-exercise-1-the-effect-of-gender-on-subjective-wellbeing" class="nav-link" data-scroll-target="#exercise-1-the-effect-of-gender-on-subjective-wellbeing">Exercise 1: The effect of <em>gender</em> on <em>subjective wellbeing</em></a>
  <ul class="collapse">
  <li><a href="#step-0-formulate-your-research-question" id="toc-step-0-formulate-your-research-question" class="nav-link" data-scroll-target="#step-0-formulate-your-research-question">Step 0: Formulate your <strong>“research question”</strong></a></li>
  <li><a href="#step-1-find-describe-and-understand-your-variables" id="toc-step-1-find-describe-and-understand-your-variables" class="nav-link" data-scroll-target="#step-1-find-describe-and-understand-your-variables">Step 1: <strong>Find, describe and understand</strong> your variables</a></li>
  <li><a href="#step-2-modify-your-variables-if-needed" id="toc-step-2-modify-your-variables-if-needed" class="nav-link" data-scroll-target="#step-2-modify-your-variables-if-needed">Step 2: <strong>Modify</strong> your variables (if needed)</a></li>
  <li><a href="#step-3-describe-the-relationship-between-your-variables" id="toc-step-3-describe-the-relationship-between-your-variables" class="nav-link" data-scroll-target="#step-3-describe-the-relationship-between-your-variables">Step 3: <strong>Describe</strong> the relationship between your variables</a>
  <ul class="collapse">
  <li><a href="#scatterplots-with-fit-line" id="toc-scatterplots-with-fit-line" class="nav-link" data-scroll-target="#scatterplots-with-fit-line"><em>Scatterplots</em> with fit line</a></li>
  <li><a href="#boxplots-to-compare-group-medians" id="toc-boxplots-to-compare-group-medians" class="nav-link" data-scroll-target="#boxplots-to-compare-group-medians"><em>Boxplots</em> to compare group medians</a></li>
  <li><a href="#descriptive-statistics-by-group" id="toc-descriptive-statistics-by-group" class="nav-link" data-scroll-target="#descriptive-statistics-by-group">Descriptive statistics by group</a></li>
  </ul></li>
  <li><a href="#step-4-model-the-relationship-between-your-variables" id="toc-step-4-model-the-relationship-between-your-variables" class="nav-link" data-scroll-target="#step-4-model-the-relationship-between-your-variables">Step 4: <strong>Model</strong> the relationship between your variables</a></li>
  <li><a href="#step-5-present-and-interpret-your-findings" id="toc-step-5-present-and-interpret-your-findings" class="nav-link" data-scroll-target="#step-5-present-and-interpret-your-findings">Step 5: <strong>Present</strong> and <strong>interpret</strong> your findings</a>
  <ul class="collapse">
  <li><a href="#coding-tip-model-summary-using-jtoolssumm" id="toc-coding-tip-model-summary-using-jtoolssumm" class="nav-link" data-scroll-target="#coding-tip-model-summary-using-jtoolssumm">Coding tip: Model summary using <code>jtools::summ()</code></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercise-2-the-effect-of-education-on-subjective-wellbeing" id="toc-exercise-2-the-effect-of-education-on-subjective-wellbeing" class="nav-link" data-scroll-target="#exercise-2-the-effect-of-education-on-subjective-wellbeing">Exercise 2: The effect of <em>education</em> on <em>subjective wellbeing</em></a>
  <ul class="collapse">
  <li><a href="#coding-tip-re-leveling-a-factor-variable-usingsjmiscref_lvl" id="toc-coding-tip-re-leveling-a-factor-variable-usingsjmiscref_lvl" class="nav-link" data-scroll-target="#coding-tip-re-leveling-a-factor-variable-usingsjmiscref_lvl">Coding tip: Re-leveling a factor variable using<code>sjmisc::ref_lvl()</code></a></li>
  </ul></li>
  <li><a href="#exercise-3-what-is-the-effect-of-education-on-subjective-wellbeing-when-we-also-control-for-sex-and-age" id="toc-exercise-3-what-is-the-effect-of-education-on-subjective-wellbeing-when-we-also-control-for-sex-and-age" class="nav-link" data-scroll-target="#exercise-3-what-is-the-effect-of-education-on-subjective-wellbeing-when-we-also-control-for-sex-and-age">Exercise 3: What is the effect of <em>education</em> on <em>subjective wellbeing</em> when we also control for <em>sex</em> and <em>age</em>?</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Worksheet 8</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('right', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
</div>
</div>
<hr>
<pre><code>Timetable week: 13
Topic: "Modelling numeric outcomes 2: multiple predictors"</code></pre>
<hr>
<section id="intro" class="level1">
<h1>Intro</h1>
<p>Last week we’ve learnt how to write a simple linear regression model to assess the statistical relationship between two <strong><em>numeric</em></strong> (<strong><em>continuous</em></strong>) variables. The aim of the <strong>simple linear regression model</strong> is to predict the expected values of one <strong><em>continuous</em></strong> (<strong><em>numeric</em></strong>) variable (e.g.&nbsp;a child’s <em>age</em>) from another <strong><em>continuous</em></strong> (<strong><em>numeric</em></strong>) variable (e.g.&nbsp;the child’s <em>height)</em>. This week we begin expanding this basic approach into more complex models by considering some changes to the <em>predictor</em> (<em>independent</em>) variable. <strong>First</strong>, we look at what happens if our aim is to model variation in a <em>numeric</em> outcome variable from a <em>dichotomous</em> (<em>binary</em>) predictor variable (e.g.&nbsp;<strong>yes</strong>/<strong>no</strong> answers, a binary <em>sex</em> variable, etc.); <strong>Then</strong>, we look at examples where the <em>predictor</em> variable is <em>categorical</em>, with more than just two categories; <strong>Finally</strong>, we add several <em>pradictor</em> variables into the model to account for the combined effect of those several factors on our <em>outcome</em> of interest.</p>
<p>For continuity, we will make use of some of the variables from previous weeks, from the same data from Wave 8 (2016-2017) of the <a href="https://www.understandingsociety.ac.uk/documentation/mainstage">UK Household Longitudinal Study (UKHLS/Understanding Society) Main Survey</a>.</p>
</section>
<section id="readings" class="level1">
<h1>Readings</h1>
<p>Core readings:</p>
<ul>
<li>Gelman et al.&nbsp;(2020): Chapter 10 and Appendix B (pp.&nbsp;131–150; 493–496)</li>
</ul>
<p>Secondary readings:</p>
<ul>
<li>Agresti (2018): Chapters 10–11 (pp.&nbsp;287–337)</li>
</ul>
<p>Further readings:</p>
<ul>
<li>Gelman et al.&nbsp;(2020): Chapters 11 and 12 (pp.&nbsp;153–211)</li>
<li>Agresti (2018): Chapters 12–14 (pp.&nbsp;351–450)</li>
</ul>
<p><svg aria-hidden="true" role="img" viewbox="0 0 448 512" style="height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M48 96V416c0 8.8 7.2 16 16 16H384c8.8 0 16-7.2 16-16V170.5c0-4.2-1.7-8.3-4.7-11.3l33.9-33.9c12 12 18.7 28.3 18.7 45.3V416c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V96C0 60.7 28.7 32 64 32H309.5c17 0 33.3 6.7 45.3 18.7l74.5 74.5-33.9 33.9L320.8 84.7c-.3-.3-.5-.5-.8-.8V184c0 13.3-10.7 24-24 24H104c-13.3 0-24-10.7-24-24V80H64c-8.8 0-16 7.2-16 16zm80-16v80H272V80H128zm32 240a64 64 0 1 1 128 0 64 64 0 1 1 -128 0z"></path></svg> <a href="https://github.com/CGMoreh/SOC2069/raw/main/readings/soc2069-reading-pack.zip"><strong>Download the module reading pack from here (.zip 47MB)</strong></a></p>
</section>
<section id="exercise-0-setup" class="level1">
<h1>Exercise 0: Setup</h1>
<ol type="1">
<li><p><strong>Open the <code>R Studio</code> interface</strong> by clicking on the <em>SOC2069-Statistical-analysis<strong>.Rproj</strong></em> file included in the <strong><em>SOC2069-Statistical-analysis</em></strong> project folder that you downloaded from Canvas in Lab6. The folder should be stored on your Newcastle University <strong>OneDrive</strong> and accessible from any computer</p>
<p><svg aria-hidden="true" role="img" viewbox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M352 320c88.4 0 160-71.6 160-160c0-15.3-2.2-30.1-6.2-44.2c-3.1-10.8-16.4-13.2-24.3-5.3l-76.8 76.8c-3 3-7.1 4.7-11.3 4.7H336c-8.8 0-16-7.2-16-16V118.6c0-4.2 1.7-8.3 4.7-11.3l76.8-76.8c7.9-7.9 5.4-21.2-5.3-24.3C382.1 2.2 367.3 0 352 0C263.6 0 192 71.6 192 160c0 19.1 3.4 37.5 9.5 54.5L19.9 396.1C7.2 408.8 0 426.1 0 444.1C0 481.6 30.4 512 67.9 512c18 0 35.3-7.2 48-19.9L297.5 310.5c17 6.2 35.4 9.5 54.5 9.5zM80 408a24 24 0 1 1 0 48 24 24 0 1 1 0-48z"></path></svg> If you haven’t yet downloaded the project folder in TW11 (Lab6), then <a href="https://ncl.instructure.com/courses/48074/pages/data-access-and-description?module_item_id=2544656">download it from Canvas</a>. <strong>Tip:</strong> If you haven’t completed the Lab6 worksheet, it will be difficult to follow the next steps; please go through <em>Exercise 1</em> and <em>2</em> of <a href="https://cgmoreh.github.io/SOC2069/Worksheets/Lab6">Lab6</a>).</p></li>
<li><p><strong>Create a new blank <code>R</code> script</strong> for this lab session and call it <em>Lab8.R</em></p>
<p><svg aria-hidden="true" role="img" viewbox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M352 320c88.4 0 160-71.6 160-160c0-15.3-2.2-30.1-6.2-44.2c-3.1-10.8-16.4-13.2-24.3-5.3l-76.8 76.8c-3 3-7.1 4.7-11.3 4.7H336c-8.8 0-16-7.2-16-16V118.6c0-4.2 1.7-8.3 4.7-11.3l76.8-76.8c7.9-7.9 5.4-21.2-5.3-24.3C382.1 2.2 367.3 0 352 0C263.6 0 192 71.6 192 160c0 19.1 3.4 37.5 9.5 54.5L19.9 396.1C7.2 408.8 0 426.1 0 444.1C0 481.6 30.4 512 67.9 512c18 0 35.3-7.2 48-19.9L297.5 310.5c17 6.2 35.4 9.5 54.5 9.5zM80 408a24 24 0 1 1 0 48 24 24 0 1 1 0-48z"></path></svg> Check <em>Exercise 1, Task 2</em> of <a href="https://cgmoreh.github.io/SOC2069/Worksheets/Lab6"><em>Lab6</em></a>) if you need help with this. <strong>Tip:</strong></p>
<div class="cell" data-layout-align="center" data-fig.topcaption="true">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sheet_pics/new_script_1.jpg" class="img-fluid figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<center>
<p>or</p>
</center>
<div class="cell" data-layout-align="center" data-fig.topcaption="true">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sheet_pics/new_script_2.jpg" class="img-fluid figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div></li>
<li><p><strong>Write a comment line</strong> at the top of the new script to briefly detail what the script is about (e.g.&nbsp;<em># Script for Lab x, Week y</em>). <strong>Tip:</strong> in <code>R</code> scripts the hashtag (<em>#</em>) denotes that the text following it on the same line is just a comment, not a programming command.</p></li>
<li><p><strong>Load user-written <code>R</code> packages</strong> we commonly use with the <code>library()</code> function</p>
<p><svg aria-hidden="true" role="img" viewbox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M352 320c88.4 0 160-71.6 160-160c0-15.3-2.2-30.1-6.2-44.2c-3.1-10.8-16.4-13.2-24.3-5.3l-76.8 76.8c-3 3-7.1 4.7-11.3 4.7H336c-8.8 0-16-7.2-16-16V118.6c0-4.2 1.7-8.3 4.7-11.3l76.8-76.8c7.9-7.9 5.4-21.2-5.3-24.3C382.1 2.2 367.3 0 352 0C263.6 0 192 71.6 192 160c0 19.1 3.4 37.5 9.5 54.5L19.9 396.1C7.2 408.8 0 426.1 0 444.1C0 481.6 30.4 512 67.9 512c18 0 35.3-7.2 48-19.9L297.5 310.5c17 6.2 35.4 9.5 54.5 9.5zM80 408a24 24 0 1 1 0 48 24 24 0 1 1 0-48z"></path></svg> Check <em>Exercise 1, Task 4</em> of <a href="https://cgmoreh.github.io/SOC2069/Worksheets/Lab6"><em>Lab6</em></a> if you need help with this. <strong>Tip:</strong> You may need to first install the package with the <code>install.packages()</code> function if it’s not yet installed</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># If you need to first install the packages, remove the hashtag </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   from in front of the `install.packages()` command to un-comment it </span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   and run it</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("tidyverse", "mosaic", "sjmisc"))     </span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjmisc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We'll also install a new package that contains some nice functions </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   for better formatted table outputs and graphing of regression models   </span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"jtools"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
</ol>
<ol start="5" type="1">
<li><p><strong>Load the <em>ukhls_w8.rds</em> dataset</strong> to an object in the session Environment; let’s call that object “ukhls”:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>ukhls <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"ukhls_w8.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><svg aria-hidden="true" role="img" viewbox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M352 320c88.4 0 160-71.6 160-160c0-15.3-2.2-30.1-6.2-44.2c-3.1-10.8-16.4-13.2-24.3-5.3l-76.8 76.8c-3 3-7.1 4.7-11.3 4.7H336c-8.8 0-16-7.2-16-16V118.6c0-4.2 1.7-8.3 4.7-11.3l76.8-76.8c7.9-7.9 5.4-21.2-5.3-24.3C382.1 2.2 367.3 0 352 0C263.6 0 192 71.6 192 160c0 19.1 3.4 37.5 9.5 54.5L19.9 396.1C7.2 408.8 0 426.1 0 444.1C0 481.6 30.4 512 67.9 512c18 0 35.3-7.2 48-19.9L297.5 310.5c17 6.2 35.4 9.5 54.5 9.5zM80 408a24 24 0 1 1 0 48 24 24 0 1 1 0-48z"></path></svg> Check <em>Exercise 1, Task 4</em> of <a href="https://cgmoreh.github.io/SOC2069/Worksheets/Lab6"><em>Lab6</em></a>) if you need help with this. <strong>Tip:</strong> Specifying only the file name without a path assumes that you have followed Step 1 above correctly and your working directory is the RProject. If not, go back to Step 1.</p>
<p><span style="color:red"><svg aria-hidden="true" role="img" viewbox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M352 320c88.4 0 160-71.6 160-160c0-15.3-2.2-30.1-6.2-44.2c-3.1-10.8-16.4-13.2-24.3-5.3l-76.8 76.8c-3 3-7.1 4.7-11.3 4.7H336c-8.8 0-16-7.2-16-16V118.6c0-4.2 1.7-8.3 4.7-11.3l76.8-76.8c7.9-7.9 5.4-21.2-5.3-24.3C382.1 2.2 367.3 0 352 0C263.6 0 192 71.6 192 160c0 19.1 3.4 37.5 9.5 54.5L19.9 396.1C7.2 408.8 0 426.1 0 444.1C0 481.6 30.4 512 67.9 512c18 0 35.3-7.2 48-19.9L297.5 310.5c17 6.2 35.4 9.5 54.5 9.5zM80 408a24 24 0 1 1 0 48 24 24 0 1 1 0-48z"></path></svg> If you have accidentally overwritten the original dataset with incorrect transformations to variables, you can download the original dataset again from here: </span> <strong><a href="https://cgmoreh.github.io/SOC2069/SOC2069-Statistical-analysis/ukhls_w8.rds">https://cgmoreh.github.io/SOC2069/SOC2069-Statistical-analysis/ukhls_w8.rds</a></strong>. <span style="color:red">Save it to the project folder, replacing the old dataset.</span></p></li>
</ol>
</section>
<section id="exercise-1-the-effect-of-gender-on-subjective-wellbeing" class="level1">
<h1>Exercise 1: The effect of <em>gender</em> on <em>subjective wellbeing</em></h1>
<p><code>About 60  minutes</code></p>
<hr>
<p>We will follow the same “0 + 5”-step workflow as in <strong>Lab7</strong>. First (<strong>“Step 0”</strong>), state the research question; then (<strong>Step 1</strong>) find and understand variables (data) that help you answer that question; then (<strong>Step 2</strong>) modify (wrangle) any variables that need to be adjusted to help the analysis and interpretation; then (<strong>Step 3</strong>) describe how your <em>outcome</em> variables and main <em>predictor</em> variable(s) are related. This will help with the interpretation of the statistical results and with identifying any further changes to the variables that may be needed (returning to Step 2 again). You may also wish to check the relationship between your predictor variables if you have more than one; then (<strong>Step 4</strong>) apply the statistical model that is most appropriate to answer the “research question”; and finally (<strong>Step 5</strong>) summarise the results from your analysis using tables, figures and your own words. In each exercise, we’ll go step-by-step.</p>
<section id="step-0-formulate-your-research-question" class="level2">
<h2 class="anchored" data-anchor-id="step-0-formulate-your-research-question">Step 0: Formulate your <strong>“research question”</strong></h2>
<p>The title of the exercise is almost a reasonable sounding research question. We want to understand: _“Does <em>gender</em> have an effect on <em>subjective wellbeing</em>”? Or, formulated differently: “Are there any <em>gender</em>-based differences in <em>subjective wellbeing</em>? Or:”Are <em>women</em> happier than men?“.</p>
<p>All of these are similar in their aim and the methods required to answer then, but choosing one over the other means that we need to pay attention to how we interpret our results and formulate our answers later on.</p>
</section>
<section id="step-1-find-describe-and-understand-your-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-1-find-describe-and-understand-your-variables">Step 1: <strong>Find, describe and understand</strong> your variables</h2>
<p>Last week (see <strong>Lab7</strong>) we got to know how <em>subjective wellbeing</em> is defined and operationalised, and which variable in our UKHLS dataset measures it: <strong>scghq1_dv</strong>.</p>
<p>The other variable we need to answer our question is one that measures respondents’ <em>gender</em>. We have a variable in the dataset called <strong>sex</strong> that best approximates this (we’ll disregard conceptual differences between <em>sex</em> and <em>gender</em> here; we could have used <em>sex</em> instead of <em>gender</em> in our research question to be more precise, but that would have sounded a bit awkward and probably changed its meaning completely <svg aria-hidden="true" role="img" viewbox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;"><path d="M464 256A208 208 0 1 0 48 256a208 208 0 1 0 416 0zM0 256a256 256 0 1 1 512 0A256 256 0 1 1 0 256zm177.6 62.1C192.8 334.5 218.8 352 256 352s63.2-17.5 78.4-33.9c9-9.7 24.2-10.4 33.9-1.4s10.4 24.2 1.4 33.9c-22 23.8-60 49.4-113.6 49.4s-91.7-25.5-113.6-49.4c-9-9.7-8.4-24.9 1.4-33.9s24.9-8.4 33.9 1.4zM144.4 208a32 32 0 1 1 64 0 32 32 0 1 1 -64 0zm192-32a32 32 0 1 1 0 64 32 32 0 1 1 0-64z"></path></svg>).</p>
<p>We have already looked at the <strong>sex</strong> variable in <strong>Lab6, Task 3.1</strong>. So there’s nothing new that we need to do here, but let’s look again at some descriptive statistics for these two variables:</p>
<div class="notebox note">
<p><strong>Note</strong></p>
<p>You have already loaded the UKHLS dataset into your RStudio Environment in <em>Exercise 0</em> above. You can check the Environment pane in RStudio to make sure that the data is there (recall, we gave it the name “ukhls”).</p>
<p>Remember, you can check the list of variables in the dataset on this page: <a href="https://cgmoreh.github.io/SOC2069/Data/ukhls_w8" target="_blank">https://cgmoreh.github.io/SOC2069/Data/ukhls_w8</a>. (<strong>Tip</strong>: you can search for keywords in the usual way: <code>ctrl+F</code> on Windows / <code>command+F</code> on Mac, and search for “wellbeing”).</p>
</div>
<div class="taskbox task">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Complete the code below</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Descriptive statistics for 'scghq1_dv':</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>...</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Descriptive statistics for 'sex':</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>...</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="questionbox question">
<p><strong>Questions</strong></p>
<p>Examine the descriptive results from the tables and charts you’ve produced and answer:</p>
<ul>
<li>What is the average (mean) subjective wellbeing score of the respondents in the dataset?</li>
<li>What does it mean to have a score of 32 on the <em>scghq1_dv</em> scale? <strong>Tip:</strong> In Lab7 we checked what exactly the <em>scghq1_dv</em> variable measures by cross-checking on <a href="https://www.understandingsociety.ac.uk/documentation/mainstage/dataset-documentation/variable/scghq1_dv" target="_blank">the UKHLS/Understanding Society website</a>.</li>
<li>Are there more women or men in the dataset?</li>
<li>What is the percentage of women in the dataset?</li>
<li>Do we need to transform/recode any of the variables? If so, why and how?</li>
</ul>
</div>
</section>
<section id="step-2-modify-your-variables-if-needed" class="level2">
<h2 class="anchored" data-anchor-id="step-2-modify-your-variables-if-needed">Step 2: <strong>Modify</strong> your variables (if needed)</h2>
<p>In Lab7 we recoded the values on the <strong>scghq1_dv</strong> variable so that <em>higher</em> values would equate <em>higher</em> subjective wellbeing. This just makes the interpretation of the variable more logical. We also renamed it to <strong>wellbeing</strong> just because the original variable name is ugly and a bother to type. We can quickly do that again here (<strong>tip</strong>: check <em>Lab7, Ex1, Step2</em> for more explanation):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract the highest value (check in the Environment if the extracted value is correct)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>maxvalue <span class="ot">&lt;-</span> <span class="fu">max</span>(ukhls<span class="sc">$</span>scghq1_dv, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)    </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># reverse the scale</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>ukhls <span class="ot">&lt;-</span> ukhls <span class="sc">%&gt;%</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">wellbeing =</span> maxvalue <span class="sc">-</span> scghq1_dv)  </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># quickly compare the two variables to make sure the recoding was correct</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>ukhls <span class="sc">%&gt;%</span> </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(scghq1_dv, wellbeing) <span class="sc">%&gt;%</span> </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># We should get this output:</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>   scghq1_dv       wellbeing    
 Min.   : 0.00   Min.   : 0.00  
 1st Qu.: 7.00   1st Qu.:23.00  
 Median :10.00   Median :26.00  
 Mean   :11.12   Mean   :24.88  
 3rd Qu.:13.00   3rd Qu.:29.00  
 Max.   :36.00   Max.   :36.00  
 NA's   :3351    NA's   :3351   </code></pre>
</div>
</div>
</section>
<section id="step-3-describe-the-relationship-between-your-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-3-describe-the-relationship-between-your-variables">Step 3: <strong>Describe</strong> the relationship between your variables</h2>
<p>In this step we’ll learn something (relatively) new. When we described the relationship between two numeric variables (<em>wellbeing</em> and <em>age</em>) in Lab7, we did it using a <em>scatterplot</em> to which we added a <em>linear regression fit line</em> (a.k.a. a <em>line of best fit</em>, <em>least squares line</em>; see <strong>Agresti (2018: 250-255)</strong>, <strong>Gelman et al.(2020: 86-87</strong>)).</p>
<p>Using a <em>scatterplot</em> to visualise the linear relationship between a <strong>dichotomous</strong>(<strong>binary</strong>) variable (<strong>sex</strong>) and the <strong>numeric</strong> variable <strong>wellbeing</strong> is not the best approach, but it can be done.</p>
<section id="scatterplots-with-fit-line" class="level3">
<h3 class="anchored" data-anchor-id="scatterplots-with-fit-line"><em>Scatterplots</em> with fit line</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(wellbeing <span class="sc">~</span> sex, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>, <span class="st">"r"</span>), <span class="at">data =</span> ukhls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Worksheet_4_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>As with the <em>wellbeing</em> by <em>age</em> scatterplot in Lab7, it doesn’t look great because the <em>wellbeing</em> scale is rather small (0-36 discrete points) and the dispersion within genders is broad; with other variables it may look a bit better and more useful. But the scatter is as we would expect: since we only have two categories/groups in the variable <em>sex</em> (males and females), the scatter dots are vertically aligned.</p>
<p>Nonetheless, with a linear regression line fitted over the scatterplot we can sense that the average <em>wellbeing</em> score of women is somewhat lower than that of the <em>men</em>.</p>
</section>
<section id="boxplots-to-compare-group-medians" class="level3">
<h3 class="anchored" data-anchor-id="boxplots-to-compare-group-medians"><em>Boxplots</em> to compare group medians</h3>
<p>It’s more appropriate to use <em>boxplots</em> when plotting <em>numeric</em> variables against <em>categorical</em> variables, and this is what you should use in the assignment to demonstrate that you know how to pick the most appropriate visualisation method.</p>
<p>We’ve already met the <em>boxplot</em> in <em>Lab7, Ex1, Step 1</em>, where we used it to visualise the <strong>scghq1_dv</strong> by itself, as a counterpart to a <em>histogram</em>. But <em>boxplots</em> are more useful when comparing the distributions of different categories within a <em>categorical</em> variable against a <em>numeric</em> scale (such as the <strong>wellbeing</strong> score of <em>males</em> vs.&nbsp;<em>females</em> within the <strong>sex</strong> variable).</p>
<p>Functions such as <code>boxplot</code> in base <code>R</code> or the <code>bwplot</code> from <code>{mosaic}</code> that we are already familiar with can be used to make <em>boxplots</em>. They make the following plots:</p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with base R `boxplot`</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(wellbeing <span class="sc">~</span> sex, <span class="at">data =</span> ukhls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Worksheet_4_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with `bwplot`</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(wellbeing <span class="sc">~</span> sex, <span class="at">data =</span> ukhls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Worksheet_4_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with `bwplot`, adding the setting ' pch = "|" ' which transforms the median dot into a line, like in `boxplot`, making the comparison easier</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(wellbeing <span class="sc">~</span> sex, <span class="at">data =</span> ukhls, <span class="at">pch =</span> <span class="st">"|"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Worksheet_4_files/figure-html/unnamed-chunk-17-3.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>We can also plot the <em>boxplots</em> horizontally, which may be more appropriate with some variables and can further ease visual comparisons. The additional settings required for each approach are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with `boxplot`, add "horizontal = TRUE"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(wellbeing <span class="sc">~</span> sex, <span class="at">data =</span> ukhls, <span class="at">horizontal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># with `bwplot` we can simply reverse the order of variables and place our categorical (factor, dichotomous) variable first. It's as if we'd say that we're modelling the sex variable on wellbeing, rather than the other way around.</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(sex <span class="sc">~</span> wellbeing, <span class="at">data =</span> ukhls, <span class="at">pch =</span> <span class="st">"|"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Worksheet_4_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Worksheet_4_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>You can choose whichever option you prefer and find most useful for the variables you are modelling.</p>
<p>We can now see more clearly that there is some sex-based difference in <em>wellbeing</em> scores, with women reporting slightly lower wellbeing than men but also showing slightly higher standard variation in their scores.</p>
</section>
<section id="descriptive-statistics-by-group" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics-by-group">Descriptive statistics by group</h3>
<p>Visual assessment is always useful because we are visual creatures after all; but our eyes can deceive. We need to look at and compare some numbers too if we want precision.</p>
<p>We already know how to produce descriptive statistics for numeric variables, and we can easily produce them by categories of categorical variables. Let’s use the <code>favstats</code> command from the <code>{mosaic}</code> package again:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(wellbeing <span class="sc">~</span> sex, <span class="at">data =</span> ukhls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>     sex min Q1 median Q3 max     mean       sd     n missing
1   male   0 24     27 29  36 25.52269 5.155753 16017    1908
2 female   0 22     25 28  36 24.36095 5.796800 19925    1443</code></pre>
</div>
</div>
<p>Note how compared to our previous use of <code>favstats</code> for single variables, when we use it to compare categories of categorical variables against a numeric scale, we place our variables on either side of the <code>~</code> operator, just as we would do in the linear regresison model command <code>lm()</code>.</p>
<p>The table lists the usual descriptive statistics for <em>wellbeing</em> for <em>men</em> and <em>women</em> separately.</p>
<div class="questionbox question">
<p><strong>Question</strong></p>
<p>So what does the table tell us about differences in <em>wellbeing</em> between sexes? For brief definitions of each statistic in the table and the boxplots, see the <a href="https://cgmoreh.github.io/SOC2069/Slides/06_Descriptives#/quartiles-and-outliers"><em>Descriptive statistics</em> lecture slides</a></p>
</div>
</section>
</section>
<section id="step-4-model-the-relationship-between-your-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-4-model-the-relationship-between-your-variables">Step 4: <strong>Model</strong> the relationship between your variables</h2>
<p>Now we have some sense of <em>gender</em>-based differences in <em>subjective wellbeing</em> (or, whether women are happier than men) in our data, but if our aim is <strong>(a)</strong> to quantify these differences and be able to make predictions of wellbeing-scores knowing one’s gender, and <strong>(b)</strong> to check the probability that these differences do not only appear in our data by pure chance (measurement error) but they actually exist in the wider UK population from which our sample data was drawn, then we need to apply a statistical model.</p>
<p>In this exercise, we assume that there is a linear relationship between <strong>sex</strong> and <strong>wellbeing</strong> and thus model it using the same linear regression formula that we are familiar with. Let’s fit the model and save the results to an object called <strong>model_ex1</strong> (to stand for our Exercise 1 model), then ask for a <code>summary()</code> of the model results:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>model_ex1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> sex, <span class="at">data =</span> ukhls)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_ex1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>
Call:
lm(formula = wellbeing ~ sex, data = ukhls)

Residuals:
    Min      1Q  Median      3Q     Max 
-25.523  -1.523   0.639   3.639  11.639 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 25.52269    0.04362  585.13   &lt;2e-16 ***
sexfemale   -1.16174    0.05858  -19.83   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.52 on 35940 degrees of freedom
  (3351 observations deleted due to missingness)
Multiple R-squared:  0.01082,   Adjusted R-squared:  0.0108 
F-statistic: 393.2 on 1 and 35940 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We are already familiar with this output from Lab7, where we modelled <em>wellbeing</em> as a function of <em>age</em>. One difference that you might have spotted if you looked carefully is <strong>the name of the predictor variable shown in the output</strong>: <em><strong>sexfemale</strong></em>. What does this represent? The women? And if so, where are the men?</p>
<div class="notebox note">
<p><strong><em>Factors</em> and other variable types in <code>R</code></strong></p>
<p><code>R</code> detects that the <code>sex</code> variable is saved in the dataset as being a <em>categorical</em> variable (i.e.&nbsp;a <strong><em>factor</em></strong> in the language of <code>R</code>). See below for more information about data/variable types in <code>R</code>:</p>
<details>
<summary>
<i><b><b>Click to View</b></b></i>
</summary>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="http://ds4ps.org/dp4ss-textbook/figures/data_types.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can check the type of each variable using the command <code>class()</code>; with the <code>str()</code> command we query the “structure” of the variable, which prints some more details about the variable; if we believe that a variable is of a certain type but we want to check, we can use functions such as <code>is.factor</code>, <code>is.numeric</code>, <code>is.character</code> etc., which will return a <em>logical</em> value (TRUE or FALSE):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check a variable's type/class:</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(ukhls<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>[1] "factor"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the structure of the variable:</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ukhls<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code> Factor w/ 2 levels "male","female": 2 2 2 1 2 2 1 1 2 1 ...
 - attr(*, "label")= chr "sex"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if a variable is a 'factor':</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(ukhls<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>[1] TRUE</code></pre>
</div>
</div>
The dataset we are using has been prepared in advance so that most of the variables are assigned the appropriate type, and we can check their types in the Variable column of the <a href="https://cgmoreh.github.io/SOC2069/Data/ukhls_w8" target="_blank">data dictionary page</a> too. But we may need to change a variable’s type at some point; we’ll learn how to do it when the problem emerges.
</details>
</div>
<div class="importantbox important">
<p><strong>Automatic releveling of <em>factor</em> variables in regression models</strong></p>
<p>Because <code>R</code> detects that the <code>sex</code> variable is as a <em>factor</em>, it treats it as such. When <code>lm()</code> encounters a factor variable with two levels/categories, it creates a new variable based on the second level. In our example, the second level is <em>female</em>, and <strong>‘sexfemale’</strong> was created automatically. It is a binary variable that takes the value <strong>1</strong> if the value of ‘gender’ <strong>is female</strong>, and <strong>0</strong> if the value of ‘gender’ <strong>is <em>not</em> female</strong> (i.e.&nbsp;is male).</p>
<p>The level coded as <strong>0</strong> is called the <strong>reference</strong> level or <strong>base</strong> level and is “absorbed” by the intercept, which is why it is not showing as a separate level/category in the list of coefficients. Just like in the <em>wellbeing</em>-by-<em>age</em> model in Lab7, where the intercept referred to <em>age</em>=0 (or to median age after we median-centred the <em>age</em> variable to give the intercept more meaning), here the intercept value refers to <em>sexfemale</em> = 0 = <em>male</em>.</p>
<p>The same automatic releveling is done in the background when the factor variable has more than two levels/categories, as we’ll see later.</p>
</div>
<p>To avoid mistakes, it is often safer to coerce a variable to a given measurement type within the model itself, which has the added advantage that the labels in the summary output will be more easily legible. We can coerce a variable to factor type with the <code>as.factor()</code> function. Compare the output from the command below to what we got previously:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ! This will overwrite the previous model object</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>model_ex1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="fu">as.factor</span>(sex), <span class="at">data =</span> ukhls)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_ex1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You will find that nothing has changed apart from the label for the female level; all the coefficients are the same.</p>
<p>If we preferred to get the regression (slope) coefficient for <em>males</em> instead of <em>females</em>, we could first relevel the sex variable by hand and then refit the model. In case of dichotomous factors (with only two levels) there is no substantive reason to do this, because the two coefficients mirror each other: if females are expected to score <strong>-1.16</strong> points lower on <em>subjective wellbeing</em> compared to the <em>males</em>, then the <em>males</em> logically are expected to score <strong>1.16</strong> points higher than the females.</p>
<p>Setting the reference category manually will be more useful with polytomous factors (those with more than two levels), as we’ll see in Exercise 2.</p>
</section>
<section id="step-5-present-and-interpret-your-findings" class="level2">
<h2 class="anchored" data-anchor-id="step-5-present-and-interpret-your-findings">Step 5: <strong>Present</strong> and <strong>interpret</strong> your findings</h2>
<p>We already gave a partial interpretation of the results in the previous paragraph. As we noted, the intercept here represents the <em>males</em>, or more specifically the average <em>subjective wellbeing</em> score for male respondents, and the slope coefficient for <em>females</em> tells us that women score 1.16-point lower than men. The regression equation is thus:</p>
<p><span class="math display">\[\widehat{wellbeing} = 25.52 - 1.16 \times 1(for\;female)\]</span></p>
<center>
or
</center>
<p><span class="math display">\[\widehat{wellbeing} = 25.52 + 1.16 \times 0(for\;male)\]</span></p>
<p>This is the same information that we got from the summary statistics by group that we did in Step 1. There we saw that the average score for males was 25.52 and the average for females was 24.36; if we ask <code>R</code> to calculate <code>24.36 - 25.52</code> for us we get -1.16, which is the regression coefficient for females from the model output.</p>
<p>But the regression modelling framework allows us to answer some deeper questions. Our aim is always to extrapolate from our sample data to the wider population from which the representative sample was drawn (here, the UK population). The <strong>Standard Error</strong>, the <strong>t value</strong>, the <strong>F-statistic</strong> and their associated <strong>p-values</strong> all refer to this step of drawing inferences about our population of interest from the actual small data that we collected.</p>
<div class="taskbox task">
<p><strong>Interpret the inferential statistics</strong></p>
<p><strong>Agresti (2018: 85-89, 114-120, 140-151, 187-190 and 321-325)</strong> and <strong>Gelman et al.&nbsp;(2020: 50-55, 57-62 and 147)</strong> provide good brief introductions and examples of these inferential statistics. Take some time to look over those pages again and examine the results from our model.</p>
</div>
<p>In this very simple bivariate example with only two variables, the <strong>t</strong> and <strong>F</strong> statistics and their <strong>p-values</strong> correspond to those we would obtain from a <strong>two-sample t-test</strong> and a one-way analysis of variance (<strong>ANOVA</strong>), respectively.</p>
<p>The <strong>t-test</strong> tests whether differences between <em>two</em> groups measured against a quantitative variable are statistically significant or not. <strong>ANOVA</strong> tests whether two <em>or more</em> population variances are statistically significantly different. In the simple case where there are only two groups, the <em>t-test</em> and the <em>ANOVA</em> measure the same thing and produce the same results, and the two are related by the simple formula: <span class="math inline">\(t^2 = F\)</span>. Our linear regression output contains both statistics, so we can check this out in <code>R</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-value for the factor variable: -/+ 19.83</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">19.83</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># F-statistic: 393.2</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>F <span class="ot">&lt;-</span> <span class="fl">393.2</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Is the statement "t squared (and rounded to one decimal point) equals F" true?</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(t<span class="sc">^</span><span class="dv">2</span>, <span class="dv">1</span>) <span class="sc">==</span> F</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>[1] TRUE</code></pre>
</div>
</div>
<p>We can also run a <em>t-test</em> or an <em>ANOVA</em> with our data using the commands below:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A t-test; to get exactly the same test statistic as in the regression, we must assume that the variances in the two groups are equal ('var.equal=TRUE')</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(wellbeing <span class="sc">~</span> sex, <span class="at">data =</span> ukhls, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>
    Two Sample t-test

data:  wellbeing by sex
t = 19.83, df = 35940, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group male and group female is not equal to 0
95 percent confidence interval:
 1.046915 1.276567
sample estimates:
  mean in group male mean in group female 
            25.52269             24.36095 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># An ANOVA model; we can view its summary() just as with the lm() models</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(wellbeing <span class="sc">~</span> sex, <span class="at">data =</span> ukhls) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>               Df  Sum Sq Mean Sq F value Pr(&gt;F)    
sex             1   11984   11984   393.2 &lt;2e-16 ***
Residuals   35940 1095238      30                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
3351 observations deleted due to missingness</code></pre>
</div>
</div>
<p>Take a minute to compare the outputs and the statistics.</p>
<p>T-tests and ANOVAs are very commonly used in disciplines where data from randomized experiments is prevalent. In sociology, this is less often the case, as sociological data are usually observational (non-experimental), complex, large, and most of the variables we are interested in are measured on <em>categorical</em> and <em>ordinal</em> scales rather than continuous <em>numeric</em> scales with statistically well-defined distributional characteristics. We are more likely to encounter t-values and F statistics as part of broader regression models rather than as the maim methods of analysis. But we have seen in the example above how these statistics relate to each other. As we will see in later exercises, regression models are particularly useful because they can be extended significantly to cases and questions that simple statistical tests cannot tackle. But in terms of the aim of drawing inferences about a wider unobserved population from a small observed set of data, the logic these tests underpins more complex models.</p>
<p>In the classical null-hypothesis significance-testing framework, both the <strong>t-test</strong> and the <strong>F test</strong> set up the “null hypothesis” (<span class="math inline">\(H_0\)</span>) that differences between the groups (here males and females) are nil or very close to zero; in other words, that the groups are equal in respect to <em>subjective wellbeing</em>. The counterpart to this is the “alternative hypothesis” (<span class="math inline">\(H_a\)</span> or <span class="math inline">\(H_1\)</span>) that the differences are <em>not</em> equal to 0. In a hypothesis test, the deviation of the data from the null hypothesis is summarised by the <strong>p-value</strong>: the probability of observing something at least as extreme as the observed test statistic (i.e.&nbsp;the <strong>t</strong> or the <strong>F</strong> here). The possible outcomes of a hypothesis test are “reject” or “not reject.” It is never possible to “accept” a statistical hypothesis, only to find that the data are not sufficient to reject it. This wording may feel cumbersome but we need to be careful, as it is a common mistake for researchers to act as if an effect is negligible or zero, just because this hypothesis cannot be rejected from data at hand.</p>
<p>In common practice, the null hypothesis is said to be “rejected” if the p-value is <strong>less than 0.05</strong> — that is, if the 95% <em>confidence interval</em> for the parameter excludes zero. Put differently, <em>statistical significance</em> is conventionally defined as a p-value less than 0.05, relative to some null hypothesis or prespecified value that would indicate no effect present. For fitted regressions, this roughly corresponds to coefficient estimates being considered as statistically significant if they are at least two standard errors from zero, or not statistically significant otherwise.</p>
<p>Speaking more generally, an estimate is said to be not statistically significant if the observed value could reasonably be explained by simple chance variation, much in the way that a sequence of 20 coin tosses might happen to come up 8 heads and 12 tails; we would say that this result is not statistically significantly different from chance. In that example, the observed proportion of heads is 0.40 but with a standard error of 0.11 — thus, the data are less than two standard errors away from the null hypothesis of 50%.</p>
<p>In our model the <strong>p-value</strong> associated with “sexfemale” is <span class="math inline">\(&lt; 2e-16\)</span> in scientific notation, which we know from last week is a very small number that can be calculated as <span class="math inline">\(2\times10^{-16}\)</span> (in <code>R</code>: <code>(2*10)^-16 %&gt;% format(scientific = FALSE)</code> = 0.000000000000000000001525879). It is definitely well below the conventional value of <code>0.05</code>, and as the regression summary output indicates with the <code>***</code> notation, it is lower than <code>0.001</code>. This p-value tells us <em>the probability that the true test statistic in the wider population is at least as extreme as the one we found in our data, if the <span class="math inline">\(H_0\)</span> were true</em>. In other words, <strong><em>if there really was no difference at all in the average “subjective wellbeing” between men and women in the UK population, then the probability of us observing the t-value we observed in our sample data would be lower than 0.001, or 0.1%</em></strong>. So we reject the assumption that there really is no difference between men and women in the population and provisionally accept that the evdence we have points to a real diference in the population. A very common but not too informative way of expressing this result is to say that we found a <em>statistically significant</em> association between <em>gender</em> and <em>subjective wellbeing</em>, or that <em>gender</em> has a <em>statistically significant</em> effect on <em>subjective wellbeing</em>.</p>
<p>In scientific publications if you manage to find such a <code>***</code> statistical significance for your main hypothesis - the one that directly answers one of your research questions - you’ve hit the jackpot. Yet, most of our simple regressions and tests using the UKHLS to address a sociologically relevant research question are likely to be highly “statistically significant”. The reason is that our dataset is extremely large in the context of the simple tests for which null-hypothesis significance testing had been designed. We will also notice that while our p-value is very low (and therefore statistically significant), thea actual <strong>size of the effect</strong> that we measured was very moderate: the difference between the male and female scores on the <em>subjective wellbeing</em> scale was really not all that impressive. In other words, the difference may truly exist in the whole population of the UK, not only in our data. but the difference is so small as to be completely uninteresting from a practical point of view. One could ask: so what if women score 1.16 points lower on a 37-point self-reported scale? Does that really have any social implications? And, importantly, <strong>can we really be sure that the fact of being a <em>woman</em> is what truly drives this difference, or might there be other factors at stake</strong>? For example, what if <strong>income</strong> is the factor that really makes a difference, and being a women merely reflects the fact that on average they earn less than the men?</p>
<p>These are the questions that a <em>multiple regression model</em> can try to answer by accounting for the <strong>joint effect of several predictors</strong>. Before starting to develop our simple model into a multiple linear regression, reflect on what Gelman et al.&nbsp;say about <em>p-values</em> and over-reliance on statistical significance:</p>
<blockquote class="blockquote">
<p>In the fields in which we work, we do not generally think null hypotheses can be true: in social science and public health, just about every treatment one might consider will have some effect, and no comparisons or regression coefficient of interest will be exactly zero. We do not find it particularly helpful to formulate and test null hypotheses that we know ahead of time cannot be true. <strong><em>Testing null hypotheses is just a matter of data collection: with sufficient sample size, any hypothesis can be rejected</em></strong>, and there is no real point to gathering a mountain of data just to reject a hypothesis that we did not believe in the first place. That said, not all effects and comparisons are detectable from any given study. So, even though we do not ever have the research goal of rejecting a null hypothesis, we do see the value of checking the consistency of a particular dataset with a specified null model. The idea is that non-rejection tells us that there is not enough information in the data to move beyond the null hypothesis. … Conversely, the point of rejection is not to disprove the null … but rather to indicate that there is information in the data to allow a more complex model to be fit (<strong>Gelman et at. 2020: 59-60</strong>).</p>
</blockquote>
<section id="coding-tip-model-summary-using-jtoolssumm" class="level3 codebox code">
<h3 class="anchored" data-anchor-id="coding-tip-model-summary-using-jtoolssumm">Coding tip: Model summary using <code>jtools::summ()</code></h3>
<p>The base R <code>summary()</code> function is useful, but there are other functions that print model summary statistics in much nicer default formats. One that I like is the <code>summ()</code> function from the <code>{jtools}</code> package.</p>
<details>
<summary>
<i><b><b>Click to View</b></b></i>
</summary>
<p>We have installed and loaded the <code>{jtools}</code> package in <em>Exercise 0</em>, so we should have access to its functions. The basic model summary command is the following:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>jtools<span class="sc">::</span><span class="fu">summ</span>(model_ex1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By default, the output reports statistics with two decimal points precision. We can easily change that with the <code>digits=</code> option if needed (in most cases, three decimals are the most useful); another very useful option is to request <em>confidence intervals</em> instead of <em>standard errors</em> in the output with the <code>confint</code> option. Confidence intervals are much more straightforward to interpret and use than the <em>standard error</em>. The command with these options included and the output look like this:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>jtools<span class="sc">::</span><span class="fu">summ</span>(model_ex1, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">confint =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>MODEL INFO:
Observations: 35942 (3351 missing obs. deleted)
Dependent Variable: wellbeing
Type: OLS linear regression 

MODEL FIT:
F(1,35940) = 393.247, p = 0.000
R² = 0.011
Adj. R² = 0.011 

Standard errors: OLS
--------------------------------------------------------------
                      Est.     2.5%    97.5%    t val.       p
----------------- -------- -------- -------- --------- -------
(Intercept)         25.523   25.437   25.608   585.129   0.000
sexfemale           -1.162   -1.277   -1.047   -19.830   0.000
--------------------------------------------------------------</code></pre>
</div>
</div>
The package also contains a number of very useful functions for plotting the regression results to graphs and making it easier to assess them visually. We will explore that in the context of slightly more complex models later.
</details>
</section>
</section>
</section>
<section id="exercise-2-the-effect-of-education-on-subjective-wellbeing" class="level1">
<h1>Exercise 2: The effect of <em>education</em> on <em>subjective wellbeing</em></h1>
<hr>
<p>In this exercise we expand the logic of the simple linear regression model with a dichotomous predictor to cases where we have categorical predictors (i.e.&nbsp;factor variables with more than two levels). The dataset contains a variable measuring educational attainment on six levels: <code>hiqual_dv</code>. The variable looks like this:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>Highest qualification, UKHLS &amp; BHPS samples (x) &lt;categorical&gt; 
# total N=39293 valid N=38435 mean=3.07 sd=1.65

Value               |     N | Raw % | Valid % | Cum. %
------------------------------------------------------
Degree              | 10058 | 25.60 |   26.17 |  26.17
Other higher degree |  4659 | 11.86 |   12.12 |  38.29
A-level etc         |  8326 | 21.19 |   21.66 |  59.95
GCSE etc            |  7726 | 19.66 |   20.10 |  80.05
Other qualification |  3388 |  8.62 |    8.81 |  88.87
No qualification    |  4278 | 10.89 |   11.13 | 100.00
&lt;NA&gt;                |   858 |  2.18 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<div class="taskbox task">
<p><strong>Task</strong></p>
<ul>
<li>Follow the steps in Exercise 1 leading up to fitting a linear regression model. Check the relationship between <em>education</em> and <em>wellbeing</em> by producing the appropriate plots and summray statistics tables;</li>
<li>Fit a regression model similar to the one in Exercise 1. Use the <code>as.factor</code> function to tell <code>R</code> explicitly that the <em>education</em> variable is a factor. This will result in more readable factor levels in the summary output. Save the model object and name it “<strong>model_ex2</strong>”;</li>
<li>Check the summary of <em>model_ex2</em> using the <code>summ()</code> function from the <code>{jtools}</code> package, as in the coding advice block above.</li>
</ul>
</div>
<p>The final model you produce should look something like this:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>MODEL INFO:
Observations: 35267 (4026 missing obs. deleted)
Dependent Variable: wellbeing
Type: OLS linear regression 

MODEL FIT:
F(5,35261) = 18.356, p = 0.000
R² = 0.003
Adj. R² = 0.002 

Standard errors: OLS
----------------------------------------------------------------------------
                                    Est.     2.5%    97.5%    t val.       p
------------------------------- -------- -------- -------- --------- -------
(Intercept)                       25.213   25.102   25.325   443.546   0.000
as.factor(hiqual_dv)Other         -0.210   -0.409   -0.012    -2.077   0.038
higher degree                                                               
as.factor(hiqual_dv)A-level       -0.308   -0.475   -0.141    -3.619   0.000
etc                                                                         
as.factor(hiqual_dv)GCSE          -0.596   -0.767   -0.425    -6.831   0.000
etc                                                                         
as.factor(hiqual_dv)Other         -0.496   -0.723   -0.270    -4.293   0.000
qualification                                                               
as.factor(hiqual_dv)No            -0.896   -1.109   -0.683    -8.247   0.000
qualification                                                               
----------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>As in the case of simple dichotomous predictors, <code>R</code> recodes our <em>education</em> variable into six differnt dichotomous/binary variables, one for each level of educational attainment. As with the <em>sex</em> variable before, each of these new variables are coded as <strong>1</strong> for being in that educational level and <strong>0</strong> for not being in that level. For example, what appears in the summary table as “as.factor(hiqual_dv)Other higher degree” is now a dichotomous variable measured as <strong>1</strong> for having some ‘other higher degree’ and <strong>0</strong> for not having (i.e.&nbsp;having any of the other educational qualifications.) Notice that as with the <em>sex</em> variable before, the first level of the <em>hiqual_dv</em> variable (“Degree” level qualification) is left off the list of predictors. <strong>That category is now absorbed into the <em>intercept</em> and represents the reference (base) category to which the coefficients (estimates) of all the other categories compare to</strong>. With this information, you should be able to interpret the results in the table just as you have done in Exercise 1. Here are some questions to guide your interpretation:</p>
<div class="questionbox question">
<p><strong>Questions</strong></p>
<p>Examine the descriptive results from the regression model and try to answer:</p>
<ul>
<li>What does the coefficient for the ‘Intercept’ (25.213) mean here?</li>
<li>Does having a ‘Degree’-level educational qualification increase or decrease one’s expected level of subjective wellbeing?</li>
<li>What is the effect on wellbeing of having ‘no qualification’?</li>
<li>Can we compute a precise numeric value for the predicted average wellbeing-score of someone with ‘A-level etc’ qualification? If so, what is it? <strong>Tip</strong>: you can use <code>R</code> as a calculator here as we did in earlier examples</li>
<li>How are these results different from what we would get if we had instead fit an ANOVA model with the <code>aov()</code> function? Would you expect to get the same <em>F</em>-value?</li>
<li>And what do you think the <em>F</em>-test is testing in this model? <strong>Tip</strong>: check <strong>Gelman et al.&nbsp;(2020: 147)</strong>.</li>
</ul>
</div>
<section id="coding-tip-re-leveling-a-factor-variable-usingsjmiscref_lvl" class="level3 codebox code">
<h3 class="anchored" data-anchor-id="coding-tip-re-leveling-a-factor-variable-usingsjmiscref_lvl">Coding tip: Re-leveling a factor variable using<code>sjmisc::ref_lvl()</code></h3>
<p>With categorical variables we may want to change the reference category if we feel that the first category assigned as reference/base by <code>R</code> is less informative for our purposes. For example, we may want to change the reference category of the <em>education</em> variable to ‘No qualification’ and compare all the other categories to it. We could do the transformation needed by hand, and there is a function in base <code>R</code> that can do it. However, given that we have labelled factors and base <code>R</code> functions don’t handle labels well, it’s safer and quicker to rely on functions such as <code>ref_lvl()</code> from the <code>{sjmisc}</code> package that we are already familiar with.</p>
<details>
<summary>
<i><b>Click to View</b></i>
</summary>
<p>To relevel the <em>education</em> variable as described above, we would write <code>ref_lvl(hiqual_dv, lvl = 6)</code> because “No qualification” is the 6th category/level. But we should be careful not to overwrite our original variables in case we make a mistake while recoding; so it’s safer to create a new variable using the <code>mutate()</code> function we already know about. I’ll call that new variable “ref_no_qual”:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># take the data, `mutate` to create a new variable that is = to the result from the `ref_lvl` function:</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>ukhls <span class="ot">&lt;-</span> ukhls <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ref_no_qual =</span> <span class="fu">ref_lvl</span>(hiqual_dv, <span class="at">lvl =</span> <span class="dv">6</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check a frequency table of the old and new variables to see if it'sall as expected:</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>ukhls <span class="sc">%&gt;%</span> <span class="fu">frq</span>(hiqual_dv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>Highest qualification, UKHLS &amp; BHPS samples (hiqual_dv) &lt;categorical&gt; 
# total N=39293 valid N=38435 mean=3.07 sd=1.65

Value               |     N | Raw % | Valid % | Cum. %
------------------------------------------------------
Degree              | 10058 | 25.60 |   26.17 |  26.17
Other higher degree |  4659 | 11.86 |   12.12 |  38.29
A-level etc         |  8326 | 21.19 |   21.66 |  59.95
GCSE etc            |  7726 | 19.66 |   20.10 |  80.05
Other qualification |  3388 |  8.62 |    8.81 |  88.87
No qualification    |  4278 | 10.89 |   11.13 | 100.00
&lt;NA&gt;                |   858 |  2.18 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>ukhls <span class="sc">%&gt;%</span> <span class="fu">frq</span>(ref_no_qual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>ref_no_qual &lt;categorical&gt; 
# total N=39293 valid N=38435 mean=3.40 sd=1.54

Value               |     N | Raw % | Valid % | Cum. %
------------------------------------------------------
No qualification    |  4278 | 10.89 |   11.13 |  11.13
Degree              | 10058 | 25.60 |   26.17 |  37.30
Other higher degree |  4659 | 11.86 |   12.12 |  49.42
A-level etc         |  8326 | 21.19 |   21.66 |  71.08
GCSE etc            |  7726 | 19.66 |   20.10 |  91.19
Other qualification |  3388 |  8.62 |    8.81 | 100.00
&lt;NA&gt;                |   858 |  2.18 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>It all looks okay - the frequencies all add up as expected. Now let’s refit <em>model_ex2</em> with the new variable and interpret the results:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## model_ex2_refitted</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>model_ex2_refitted <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> <span class="fu">as.factor</span>(ref_no_qual), <span class="at">data =</span> ukhls)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(model_ex2_refitted, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">confint =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">normal_print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>MODEL INFO:
Observations: 35267 (4026 missing obs. deleted)
Dependent Variable: wellbeing
Type: OLS linear regression 

MODEL FIT:
F(5,35261) = 18.356, p = 0.000
R² = 0.003
Adj. R² = 0.002 

Standard errors: OLS
-------------------------------------------------------------------------------
                                       Est.     2.5%    97.5%    t val.       p
---------------------------------- -------- -------- -------- --------- -------
(Intercept)                          24.318   24.136   24.499   262.730   0.000
as.factor(ref_no_qual)Degree          0.896    0.683    1.109     8.247   0.000
as.factor(ref_no_qual)Other           0.685    0.440    0.930     5.487   0.000
higher degree                                                                  
as.factor(ref_no_qual)A-level         0.588    0.368    0.808     5.240   0.000
etc                                                                            
as.factor(ref_no_qual)GCSE            0.300    0.077    0.523     2.639   0.008
etc                                                                            
as.factor(ref_no_qual)Other           0.400    0.132    0.668     2.923   0.003
qualification                                                                  
-------------------------------------------------------------------------------</code></pre>
</div>
</div>
</details>
</section>
</section>
<section id="exercise-3-what-is-the-effect-of-education-on-subjective-wellbeing-when-we-also-control-for-sex-and-age" class="level1">
<h1>Exercise 3: What is the effect of <em>education</em> on <em>subjective wellbeing</em> when we also control for <em>sex</em> and <em>age</em>?</h1>
<hr>
<div class="taskbox task">
<p>You will probably be taking this exercise home as time is short, but if you can start it in class that would be ideal. You have free hand with this exercise, because we have covered all the code required to complete it.</p>
<p>This sounds like a real research question, not far from what social researchers usually ask and try to answer. We are already familiar with all the variables, so we don’t need to produce any new descriptive statistics (although in Lab7 we did median-centre the <em>age</em> variable, so unless you saved that dataset, you should redo that transformation for the best results).</p>
<p>In fact, what the exercise requires is for us to combine the bivariate models that we have fit in Lab7 and Lab8. The only new trick is knowing how to add new predictors to a model formula, which in <code>R</code> is accomplished using the <code>+</code> sign. The final model then should look like this:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>model_ex3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> age_median_centred <span class="sc">+</span> <span class="fu">as.factor</span>(sex) <span class="sc">+</span> <span class="fu">as.factor</span>(hiqual_dv), <span class="at">data =</span> ukhls)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>jtools<span class="sc">::</span><span class="fu">summ</span>(model_ex3, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">confint =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre class="outputbox"><code>MODEL INFO:
Observations: 35267 (4026 missing obs. deleted)
Dependent Variable: wellbeing
Type: OLS linear regression 

MODEL FIT:
F(7,35259) = 80.694, p = 0.000
R² = 0.016
Adj. R² = 0.016 

Standard errors: OLS
----------------------------------------------------------------------------
                                    Est.     2.5%    97.5%    t val.       p
------------------------------- -------- -------- -------- --------- -------
(Intercept)                       25.876   25.748   26.003   397.767   0.000
age_median_centred                 0.016    0.013    0.019     9.493   0.000
as.factor(sex)female              -1.142   -1.258   -1.025   -19.260   0.000
as.factor(hiqual_dv)Other         -0.206   -0.405   -0.008    -2.043   0.041
higher degree                                                               
as.factor(hiqual_dv)A-level       -0.292   -0.458   -0.125    -3.437   0.001
etc                                                                         
as.factor(hiqual_dv)GCSE          -0.567   -0.737   -0.397    -6.542   0.000
etc                                                                         
as.factor(hiqual_dv)Other         -0.697   -0.926   -0.468    -5.963   0.000
qualification                                                               
as.factor(hiqual_dv)No            -1.085   -1.304   -0.866    -9.703   0.000
qualification                                                               
----------------------------------------------------------------------------</code></pre>
</div>
</div>
</div>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->



</body></html>