---
title: "My assignment title"
author: "My name"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
self-contained: true
---

## Introduction

This is where I introduce the topic of my assignment, stating what I aim to find out and what my research question is.

## Literature review

This is where I place my research question in the context of existing literature, summarising what we already know about the topic based on a few academic sources (around 5 should be enough for this assignment).


## Data and methods

This is where I describe the data source that I am using to answer the research question. The data will be the same Wave 8 of the UK Household Longitudinal Study (Understanding Society) survey dataset that we have been using in the labs. Here, I'll say a few words about that data based on the information available on the survey website, and I will provide a citation of the dataset (it's all on Canvas).

I also introduce the variables that I have selected to answer the research question. I briefly describe what they measure and whether I will transform them in any way before using them in the analysis.

I also briefly state the methods I will use (what type of regression analysis, any tables/figures I include, etc.)

## Results

This is where I present my analysis, step-by-step, as I have done in the labs. This section will include:
- the code I use to produce the outputs
- the outputs that are produced
- my brief interpretation of the meaning of the outputs

To include a code chunk that will be executed as R code, I either type **ctrl** + **alt** + **i** (or **Command** + **Option** + **I** on macOS), or I click on the ***+C*** icon on this document's menu bar and select "R". The code chunk will look like this:

```{r}
# I can now use this space just like an R script editor, as I've done in the labs

```






## Discussion and conclusions

This is where I take the broader picture of what my analysis and outputs have shown and connect it back to the existing literature, stating how my findings relate to what we already know.


## References

Here I include a reference list for the literature that I cited above.


