---
title: "testing"
output:
  docx_document
#   html_document:
#     theme: lumen
#     toc: yes
#     toc_float: yes
#     toc_highlight: no
#     tabset: yes
#     number_sections: no
#     anchor_sections: no
#     self_contained: yes
#     code_download: no
#     grid:
#       margin-width: 3px
# css: labcss.css
execute: 
  # error: true
  cache: true
---

```{r}
library(easystats)
```


```{r}

datafolder <- "D:\\OneDrive - Newcastle University\\DATA\\EVS_WVS\\WVS_7"
datafile <- "WVS_Cross-National_Wave_7_spss_v5_0.7z"
d <- fs::path(datafolder, datafile)
d <- archive::archive_read(d)
# d <- archive::archive_extract(d)
# d <- archive::archive_read(d)
# wvs7zip <- datawizard::data_read(d)
wvs7 <- sjlabelled::read_spss(d)

```


```{r}
#| eval: false

## gt_preview

gt::gt_preview(wvs7)
```




```{r}
#| eval: false

# data(efc)

wvs7 |> 
  # sjlabelled::set_labels(J_INTDATE, labels = "") |>
  # data_select(J_INTDATE) |> 
  data_codebook() |> print_html(variable_label_width = 20,
                                value_label_width = 20,
                                font_size = "80%", line_padding = 0)
  
  # DT::datatable()
  
  # rmarkdown::paged_table()
  # print_html()

```

```{r}
#| eval: false

summarytools::dfSummary(wvs7)
```



```{r}
# Renders to Word

wvs7 |> 
  data_group(B_COUNTRY) |> 
  data_tabulate(Q291G1) 
# |> 
  # print_md()


```


```{r}
# Doesn't render to Word
with(wvs7, 
  sjPlot::sjt.xtab(Q57, Q260))
```


```{r}
library(tidyverse)
library(strengejacke)

wvs7s <- wvs7 |> 
  # data_extract(c(Q57, Q260)) |> 
  drop_labels() |>
  mutate(across(where(is.factor), 
                as_numeric) |> 
                as_label()
         ) 





# Renders to Word

wvs7s |> 
  gtsummary::tbl_cross(Q57, Q260,
                     percent = "row",
                     missing = "no")
```


