---
title: "Worksheet 9"
subtitle: "Working with texts and  documents"
format: 
  # docx: default # word doc in docs already edited a bit
  html: 
    code-link: true
    embed-resources: true
    fig-align: center
    # fig-width: 5
    # fig-asp: .8
    # fig-responsive: true
    code-overflow: wrap
    code-tools:
      source: false # add URL to script document to be downloaded
      toggle: false
      caption: none
execute: 
  warning: false
  error: false
  echo: true
  purl: false
knitr: 
  opts_chunk: 
    comment: ""
    prompt: false
    message: false
    strip.white: false
css: labcss.css
bibliography: references.bib
---

------------------------------------------------------------------------

```         
Timetable week: 14
Topic: "Working with texts and  documents"
```

------------------------------------------------------------------------


# Intro

In the last two weeks we looked at qualitative interviews and filed notes as sources of textual data for a qualitative analysis. But data can be more diverse, including texts, images, videos, etc. In contrast to the secondary data that we examined before - which also *already existed* and was ready for (re)analysis - the data types we are interested in this week are *primary* data, in the sense that they were not produced or collected for administrative or research purposes other than perhaps the aim of recording and archiving them for future reference (e.g. meeting records, political speeches, radio/television programme recordings etc.). They are more strictly part of the universe of *information* that permeates the social world. Of course, as with any classification exercise, many data that we as social researchers might be interested in analysing lie between pure *primary* and *secondary* types.

In the exercises below we will explore some textual data and move towards developing techniques for analysing qualitative information.


# Reading

- Grant (2018): Chapters 2–5 and 9 (pp. 10–98; 167–182)


# Exercise 1: Documents and everyday life (general discussion)

`About 15-20 minutes`

------------------------------------------------------------------------

Let's start by discussing some main points about *documents* as data sources made by Grant (2018) in this week's reading. We will focus mainly on Chapter 2 of that book, which outlines some general principles.

```{block , type = 'discussion-15'}
**Discussion**

- Why does Grant think that Scott's (1990: 12) definition of *documents* (“a document in its most general sense is a written text”) is too restrictive, and how does she define *documents*?
- Think about a research idea/topic/question that interests you personally (it can be the same one you have developed in the previous weeks) and make a list of potential *documents* that may be useful in researching that topic, either as your primary empirical material or as additional materials to combine with other data sources (e.g. surveys, interviews, as you practiced last week).
- Who might the **authors** and intended **readers** be for potential documents you listed in the previous point? (this discussion is still at a theoretical level, so you don't need to actually check any existing documents yet)
- What sources of **bias** can you think of that may affect the validity of the potential documents you have listed, and how would this influence the approach that you would take in the analysis of that material?

```



# Exercise 2: Document "sites"

`About 30 minutes + 10 minutes discussion`

------------------------------------------------------------------------

Analysing *documents* may be understood as a form of fieldwork or ‘document ethnography’. Just as ethnography helps us research people in the natural environments of their everyday lives, 'document ethnography' helps us analyse documents in *their* natural environments. Documents always exist at specific "sites" (e.g., organisations, archives, websites) and are key elements to the composition of such sites. It thus matters what kinds of sites these are, and in your own research you should explore the ‘site-specificity’ of your particular document sites. This can extend to the actual reading and textual analysis in itself – by asking not only ‘what does the document say’ or ‘what kind of information is conveyed here’ but also asking ‘what does the document do’ and ‘what happens here’. In so doing, you are encouraged to explore how some document sites can be inaccessible or obstructed, and that documents can be hidden or destroyed, or used for enabling and covering up crimes and persecution. Documents are in themselves "sites" where political and social issues are handled, and sites where we may ‘go’, analytically and methodologically speaking, to study these very issues.

In this exercise you will trace a topic of general public interest across two document sites: 1. a newspaper and 2. the UK Parliament. You will  think about how you could analyse the topic across different 'genres' and/or 'sites'.

## Task 2.1: Media discourse

Work in pairs or small groups to identify a recent topic of great public interest. Select a topic related to some recent event (something that happened over the past year) that is likely to have been discussed at some length in both the media and in the UK Parliament.

Just as in your previous practice developing research questions and search keywords, refine your search words and do a search online to find a relevant newspaper or other media (e.g. BBC reporting) report on that topic. Select one article and read through it, taking notes on the key points discussed.

```{block , type = 'questionblock'}

**Questions**

- Who is the **author** and intended **readers** of the document (i.e. article) you are reading?
- What is the **site** of the document and how does that influence the message (e.g. intended readership, whether national or local, whether 'broadsheet' or tabloid, etc.)
- What is the main issue and message?

```



## Task 2.2: Political debates

Parliaments are institutions that can directly affect laws that govern social life. In this task, explore how the topic you have identified in the previous task was discussed in the UK Parliament. Hansard online is where all UK parliamentary debates are recorded and made available to the public (https://hansard.parliament.uk/). The website provides a search engine where we can search by keyword or by the name of a Member of Parliament. You can therefore do a very broad search on a topic, or you may be interested in what a specific MP (say, your local MP) has said on a topic.

On the Hansard website, search for the topic you have looked at in the previous task by using a keyword search (just as you have done when searching for literature, you may need to test out and refine your keywords for best results). After hitting search, you can then also refine the results by dates and the House of Parliament you are most interested in. 

Choose one of the results that you find most relevant; make sure that it is relatively long - that it contains responses from several members. Open the results and read through it. Clicking on the name of the person speaking brings up some further information about their party affiliation, constituency, etc. All this may be relevant information when analysing the text.

As in the previous task, make some general notes on the text.

```{block, type = 'questionblock'}

**Questions**

- Who is the "author" and the intended "readers" of the "document"?
- What is the "site" of the document and how does that influence the message?
- How does the background of the "author" shape the message?
- What is the main issue and message and how is it framed?
- Thinking about some of the analysis principles and methods discussed by Grant (2018, Chapter 3, particularly 'thematic analysis', which we will discuss at more length next week), what are some "themes" that you see emerging from the debate you have looked at?

```

```{block , type = 'discussion-10'}
**Discussion**

- What were the main differences in the two 'documents' on the same topic?
- Were there any common or relatable 'themes' across the two?
- How could you combine the two types of sources in your analysis?

```



# Exercise 3: Exploring the Internet Archive and the Wayback Machine

`About 40 minutes including discussion around questions`

------------------------------------------------------------------------

The internet holds vast resources of document materials that we can explore. Websites are often most valuable both for background and general reference and as empirical sources in their own right. Yet websites often also change, which means that we might lose important data or never find it in the first place. [**The Internet Archive** (www.archive.org)](www.archive.org) was founded to harvest the web and routinely store the recent version of key websites, so that researchers, journalists and the general public can visit websites of the past. The technical application enabling this harvesting and storage is called the **Wayback Machine**. Millions of websites are now stored here. In addition, other archival institutions are making their digital collections available from the Internet Archive.

## Task 3.1: Explore topics *way back*

Think again about some of your sociological interests and about what online materials may exist that could be useful in a research project on that topic, either as sources of primary textual data or as background information; you can do it individually or in pairs/small groups to exchange ideas. Choose one key website of relevance to your study or research project idea. Keep in mind that it has to be of certain general societal significance to be chosen for storage at the Internet Archive. Familiarise yourself with the Internet Archive and check if you find ‘your’ website there (if not, choose one more generally related to your own case).

```{block Question 1, type = 'questionblock'}

**Questions**

- How has the website changed over time?
- What changes are the most notable?
- What can these changes tell you about the case you are currently studying?
- Why do you think the site has changed the way it has?
- Who owns, maintains and edits the site?
- Who are its main audience, and what do you find to be its main purpose?
- What role does this website play in ongoing issues (or has played in issues of the past)?

```

## Task 3.2: Archive websites of interest

The *Wayback Machine* is also a useful tool to archive any online material that you use and cite in your research. This can ensure that online information that you reference in your writing will have an archived imprint that your readers can check for themselves. That is the main aim of employing academic referencing standards in our writing. But even if we reference our sources correctly, online sources may change or become unavailable over time. This is the challenge compared to academic sources such as journal articles or published books.

Choose one website relevant to your study and register it for harvesting with the Wayback Machine. See here for how to save copies of pages you are interested in: https://help.archive.org/help/save-pages-in-the-wayback-machine/#. Read some more about how Wayback Machine works and how you could take advantage of what it offers in your own research (https://help.archive.org/help/category/the-wayback-machine/).

```{block , type = 'questionblock'}

**Questions**

- How can you use the materials you are now collecting with the Wayback Machine?
- What can the multiple snapshots you gain tell you about the changes potentially taking place at the website, and how can this in turn tell you something about the actors, institutions and issues to which it is linked?
- How does the Wayback Machine actually work? What alternative applications you can use for the same purpose?
- How would you assess the credibility of the Internet Archive? Why or why not would you consider using it in your own work?

```

