---
title: "Worksheet 7"
subtitle: "Observation: ethnographic fieldwork"
format: 
  # docx: default # word doc in docs already edited a bit
  html: 
    code-link: true
    embed-resources: true
    fig-align: center
    # fig-width: 5
    # fig-asp: .8
    # fig-responsive: true
    code-overflow: wrap
    code-tools:
      source: false # add URL to script document to be downloaded
      toggle: false
      caption: none
execute: 
  warning: false
  error: false
  echo: true
  purl: false
knitr: 
  opts_chunk: 
    comment: ""
    prompt: false
    message: false
    strip.white: false
css: labcss.css
bibliography: references.bib
---

------------------------------------------------------------------------

```         
Timetable week: 7
Topic: "Observation: ethnographic fieldwork"
```

------------------------------------------------------------------------

# Learning outcomes

-   Understand the principles and practice of asking research questions that are best addressed using an ethnographic approach
-   Develop skills for designing an ethnographic study focusing on observation and note-taking
-   Understand the importance of field-notes and how to use them in practice

# Introduction

In this lab we focus on ethnographic research and some of its main empirical tools: *observation*, *participation* and *field-notes*. The lecture provided a broad introduction to ethnographic practice and highlighted some examples using the lecturer's own research. In this lab, you will discuss and critique some of the methodological aspects of two of the lecturer's published articles, and using the assigned methodological readings you will design a short non-participant observational study to be carried out in the university library over the next few weeks. You will use the "field-notes" taken as part of this observational exercise in Week 10 (Interpretation: analysis and writing)

# Exercise 1: Discussion and critique

`About 40  minutes`

------------------------------------------------------------------------

Working in groups of three, discuss and compare the methodological aspects of the two articles below:

-   @Moreh2014PrestigeStatusMigration "Prestige and Status in the Migration Process: The Case of Social Differentiation in a Romanian 'Community' in Spain." Journal of Ethnic and Migration Studies 40(11):1758--78. Available here: [https://www.chrismoreh.com/publication/2014-jems/2014-jems-txt.pdf](https://www.chrismoreh.com/publication/2014-jems/2014-jems-txt.pdf)

-   @Moreh2016InhabitingHeritageLiving "Inhabiting Heritage: Living with the Past in the Albayzín of Granada." Open Library of Humanities 2(1). Available here: [https://olh.openlibhums.org/article/id/4416/](https://olh.openlibhums.org/article/id/4416/)

The development of the research projects that underpin these two articles was already discussed in the lecture, but here your task is to focus on how the methodology presented in the lecture comes across in the published results. These two articles are in no way meant to exemplify best practices in ethnographic observational research, but are purely meant as examples of how one researcher addressed two different research topics by using different approaches to ethnographic fieldwork. You are asked to put on your sharpest critical lens when reading and assessing the methodological approaches presented in these articles.

Focus your group discussion on the following questions:

-   What were the main 'theoretical' or 'conceptual' aims of the two articles?

-   How does the chosen methodology relate to the main research questions that the articles aim to address?

- How does the author connect "methods" and "findings" in each of the articles?

-   How is "ethnographic" research carried out in the context of the two different projects? What are the differences? What are the similarities? What does this tell you about the multiplicity of forms that ethnographic research can take?

-   What are your methodological criticisms of the articles? What would you have done differently if you were to design that research study?

# Exercise 2: Planning an ethnographic study

`About 40  minutes`

------------------------------------------------------------------------

In a small group of 3 or 4, draw up a plan for a short ethnographic observational fieldwork to be carried out in the university library at various times over the next two weeks.

For this exercise, you will want to rely on all the readings assigned for this week. Particularly, Chapter 12 (**"*Rigorous ethnography"*,** by Federico Varese) in @GërxhaniEtAl2022HandbookSociologicalScience provides a good overview of how to undertake a rigorous ethnographic study, which requires careful planning while allowing to maintain your focus open and flexible to any emergent and unexpected questions, which is a core strength of ethnographic research. In @EmersonEtAl2011WritingEthnographicFieldnotes you will find detailed guidance on how to approach taking "jottings" and field-notes , a core element of data collection during ethnographic fieldwork.

In your planning, consider the following:

-   Come up with a "research question" that you would like to focus your ethnographic observation on. This question can be anything, as long as the field site is the university library. You can think about a "group" you would like to study (e.g. students, library staff, etc), or a phenomenon (e.g. using the library for other purposes than purely "studying"), or a specific activity (e.g. interactions between staff and students at the reception desk), or anything else!

-   Think about some "theoretical" of "conceptual" framework for your research question(s). This sounds more complicated than what it would look like in practice, but for this you can rely on other readings/theories from other modules that may apply. For example, the library can be perceived as an institutional site within a higher education institution, and the [video about using Institutional Ethnography as a Qualitative Research Method to Explore Higher Education Institutions](https://methods-sagepub-com.libproxy.ncl.ac.uk/video/using-institutional-ethnography-as-a-qualitative-research-method-to-explore) included in the Further resources describes how an "institutional" conceptual framework can be adopted.

- Think more carefully about *when* and *how* you will be conducting your observations. For example: What aspects of "library life" would you be focusing your observation and note-taking on? What methods would you be using for "jotting" down immediate observations and descriptions? Chapters 1 and 2 from @EmersonEtAl2011WritingEthnographicFieldnotes can be very useful for thinking through the various issues you may need to consider in advance of your fieldwork.


# Exercise 3: Carry out a brief observational study

`Outside class`

------------------------------------------------------------------------

Individually, carry out the ethnographic observation that you planned in Exercise 2 over the next two weeks. Make sure to take many field-notes as you will be asked to bring them with you to the lab in Week 10, when we will practice analysing and writing up "findings" form qualitative data. 


