---
title: "Worksheet 10"
subtitle: "Analysing qualitative data"
format: 
  # docx: default # word doc in docs already edited a bit
  html: 
    code-link: true
    embed-resources: true
    fig-align: center
    # fig-width: 5
    # fig-asp: .8
    # fig-responsive: true
    code-overflow: wrap
    code-tools:
      source: false # add URL to script document to be downloaded
      toggle: false
      caption: none
execute: 
  warning: false
  error: false
  echo: true
  purl: false
knitr: 
  opts_chunk: 
    comment: ""
    prompt: false
    message: false
    strip.white: false
css: labcss.css
bibliography: references.bib
csl: sociology.csl
---

------------------------------------------------------------------------

```         
Timetable week: 15
Topic: "Analysing qualitative data"
```

------------------------------------------------------------------------

# Intro

This week we turn to analysing the qualitative data collected through the various methods we covered in the previous three weeks (observational field-notes, interview and focus-group recordings, and documentary materials). Analysing qualitative data is a complex process involving organizing and categorizing the empirical materials and interpreting their meaning with reference to theoretical frameworks and guiding concepts. There are many ways in which this can be done. @kara2015 [p. 102] lists the following methods:

-   **content analysis**: a semi-quantitative technique for counting the number of instances of each category or code (Robson 2011: 349)
-   **thematic analysis**: identifying themes from coded data (Robson 2011: 475)
-   **narrative analysis**: analysing stories from primary or secondary data (Bryman 2012: 582)
-   **conversation analysis**: detailed analysis of the verbal and non-verbal content of everyday interactions (Bryman 2012: 527)
-   **discourse analysis**: analysing patterns of speech and interaction in a detailed and sometimes semi-quantitative way, for example by measuring the length of pauses (Bryman 2012: 529)
-   **metaphor analysis**: analysing metaphors from primary or secondary data (Fletcher 2013: 1555--6)
-   **phenomenological analysis**: analysing participants' stories from, and descriptions of, their 'life-worlds', or individual experiences and perceptions, with a focus on meaning (Papathomas and Lavallee 2010: 357; Mayoh, Bond and Todres 2012: 28)
-   **life course analysis**: analysis of the 'interaction between individual lives and social change' (Brittain and Green 2012: 253).

As @kara2015 [p.102] notes, the above is by no means an exhaustive list, but merely an illustration of the great range and diversity of approaches for analysing qualitative data. The choice for any particular analytical approach will depend on the type of the data collected, the aims of the research, and theoretical considerations.

In this workshop we will focus on one of the simplest and most commonly utilised methods for qualitative data analysis: *thematic analysis*. This approach relies on *thematic coding* of the data, and we will focus on this technique. We will rely here most heavily on the rich description of @GersonDamaske2020ScienceArtInterviewing \[Chapter 6\] and the concepts and guidance provided by @Neuman2014SocialResearchMethods [Chapter 14] [(Available via the library)](https://libsearch.ncl.ac.uk/permalink/f/1jraif3/NCL_ALMA2162194800002411).

# Readings

Core readings:

-   Gerson and Damaske (2020): Chapters 6 and 7 (pp. 143--193)
-   Neuman (2014): Chapters 14 (*Analysis of Qualitative Data*) and 15 (*Writing the Research Report and the Politics of Social Research*) (pp. 477--546)

<!-- SHIFT+CNTRL+C to comment out -->

# Exercise 1: Example coding of 'EU Kids Online'

`About 30  minutes + questions and discussion`

------------------------------------------------------------------------

We return to one of the example projects we looked at on Worksheet 8: the "EU Kids Online" project and their qualitative toolkit resources: <https://www.lse.ac.uk/media-and-communications/research/research-projects/eu-kids-online/toolkit/qualitative-research>.

You should already be familiar with the description of the project, its aims, methodology and data collection instruments from previous weeks. To remind yourself of those instruments, you can open the *Individual interview topic guide* and the *Focus group topic guide* and have a quick look through them.

In this exercise we will focus on the resources related to *coding* the primary qualitative material obtained from the interviews and focus groups. The research team provides a good guide on how the analysis took place, so the first task is to open their [Technical report](https://www.lse.ac.uk/media-and-communications/assets/documents/research/eu-kids-online/toolkit/qualitative-research/QualitativeMethodReport.pdf) on the qualitative research. The project was a complex cross-national comparative study involving several researchers, interviewers, data coders, translators and analysts. For this reason, the project leaders provide some good guidance to the various people involved in the analysis.

## Task 1: Read and discuss the approach to analysis

-   Read Pages 9-13 of the [Technical report](https://www.lse.ac.uk/media-and-communications/assets/documents/research/eu-kids-online/toolkit/qualitative-research/QualitativeMethodReport.pdf)
-   Read the [Instructions for first level coding of the pilot interviews](https://www.lse.ac.uk/media-and-communications/assets/documents/research/eu-kids-online/toolkit/qualitative-research/Coding-Pilot-Procedure.pdf) document

Spend about 20 minutes reading through the two documents and try to answer the questions below.

```{block Question 1, type = 'questionblock'}
**Questions**

- Data was collected in several European countries. Was all the qualitative interview/focus group data translated into English for analysis? What motivated the researchers' decision in respect to translation of materials?
- What were the aims of the *pilot* study? Thinking about the feedback from the pilots, was it a useful exercise? Do you think your own dissertation research may benefit from a *piloting* phase? How would you go about it?
- How many *levels* of coding were included as part of analysis, and what was the purpose of each *level*?
- How many researchers were involved in *first-level* coding <u>the same</u> transcripts? Were there any exceptions to this?
- Did the researchers use any software to perform the coding? 
- Were the *codes* developed before-hand, or did they emerge through the process of analysis? 

```

## Task 2: First-level coding

-   Read the [Example of first level coding](https://www.lse.ac.uk/media-and-communications/assets/documents/research/eu-kids-online/toolkit/qualitative-research/Coded-Transcript-FG-12-13-girls-Belgiun.pdf) of a focus-group transcript from Belgium.

The transcript is in the original language (Dutch), but the side comments (i.e. **codes**) are in English. Spend some time reading the comments in order. They are short, so you should be able to go through the whole documents relatively quickly. See if you can discover some of the general sentiments, ideas, information of the group interview by reading only the coding comments. Note down your own comments on what you think are the main issues raised by the interviewees/discussants.

```{block , type = 'discussion'}
**Discussion**

Based only on your reading of the side comments, what are the main issues that emerge from the focus group discussion?

How do you think that the participants' personal characteristics have affected these emerging issues, themes? (hint: look again at the English-language overview section at the start of the transcript)
```

## Task 3: Second-level coding

We know from the technical report we read earlier that some of the thematic codes were developed before the analysis or at the piloting stage, while other thematic codes have emerged from the first-level coding procedure itself. This is usually what happens in most qualitative research: you are initially guided by your research questions, other existing empirical literature and the theoretical underpinnings of your project towards paying attention to certain 'matters', 'issues', 'topics' etc. Research instruments are usually designed with some idea of what topics will emerge. All these are *higher level codes* that frame your analysis from the start. Some may not come up at all in the empirical material and may be discarded or changed later. But other important issues, themes, etc. may come to light from the empirical material itself, during *first-level coding*. The task of the analysis is to maintain an interactive relationship between these different *levels*.

In this task, explore some of the *second-level* coding employed by the research team:

-   Read the [Definitions related to the second level coding](https://www.lse.ac.uk/media-and-communications/assets/documents/research/eu-kids-online/toolkit/qualitative-research/Qualitative-Analysis-definitions.pdf)
-   Read the [Overview](https://www.lse.ac.uk/media-and-communications/assets/documents/research/eu-kids-online/toolkit/qualitative-research/Coded-Excel-overview-example-Romania.pdf) and [close up](https://www.lse.ac.uk/media-and-communications/assets/documents/research/eu-kids-online/toolkit/qualitative-research/Coded-Excel-close-up-example-Romania.pdf) examples of second level coding

Look at a few pages of the first-level coding transcript from the previous task and attempt to match the notes on the page to the second-level codes described in the documents you have just read.

# Exercise 2: Coding primary qualitative data

`About 20 minutes including discussion; if you do not have any primary data with you to analyse, you can continue to Exercise 3.`

------------------------------------------------------------------------

Now that you have seen examples of thematic coding of secondary data, apply the approaches you read about in the previous exercise to your own data. You can only complete this exercise if you have brought with you (either) your *observational notes* carried out as part of Exercise 3 on Worksheet 7, or an *interview transcript* resulting from Exercise 3 on Worksheet 8.

Analysing qualitative data requires a thorough and intimate familiarity with the data collection process. Working with primary qualitative data - data created by you - allows you insights into the data that you would not have available when analysing data collected by others as part of a research project designed by others. Much of the interpretative power employed during data analysis comes from this proximity to the research design and data collection.

```{block, type = 'questionblock'}
**Questions**

- Do you have any *codes* in mind even before looking at your data, based on the research question/topic that the data collection sought to address?
- What new *first-level* and *second-level* codes did you identify?
- How has your knowledge of the data collection process influence your approach to coding and analysis?

```

# Exercise 3: Start work on Assignment 2

`About 45 minutes including discussion in class; continue outside class`

------------------------------------------------------------------------

In this exercise we turn to the qualitative data that will be used in *Assignment 2.*

The secondary qualitative datasets that you will use as part of the thematic coding exercise in Assignment 2 come from the following three research projects:

-   **Wrighton**, Sam J (**2021**) \"The Annexation of Populations: A New State Strategy, 2017-2021\" [https://doi.org/10.5255/UKDA-SN-854598Links to an external site.](https://doi.org/10.5255/UKDA-SN-854598)

-   **Einarsdottir**, Anna and Mumford, Karen and Birks, Yvonne and Lockyer, Bridget and Sayli, Melisa and Jeep, Sudthasiri (**2021**) **\"LGBT+ Networks, 2017-2020\"** [https://doi.org/10.5255/UKDA-SN-855322Links to an external site.](https://doi.org/10.5255/UKDA-SN-855322)

-   **Pearce**, Sioned and Fox, Stuart (**2020**) \"Young people and Brexit 2017\" [https://doi.org/10.5255/UKDA-SN-854031Links to an external site.](https://doi.org/10.5255/UKDA-SN-854031)

You can read about the studies and their methodology via the links. Make sure you read through all the details available in order to understand what each study's objectives were, how the research was undertaken, and what kinds of data the researchers made publicly available.

You will have to **choose one** study to focus on, depending on which topic is of more interest to you.

Some of the projects have used mixed methods and resulted in a combination of different types of data (survey datasets, interviews, web-scraped documents, meeting notes). For this assignment exercise, only the **interview transcript data** is made available on Canvas and is to be used. This will ensure that the analyses are more comparable and easier to mark fairly.

The datasets and selected relevant documentation (data lists, interview guides, participant information sheets, etc.) are [**available via Canvas**](https://ncl.instructure.com/courses/53153/modules "Takes to external Canwas website. login required.").

In this exercise you will practice first-level coding on **one** of the interview **transcript**s from one of the three projects. **You will be working together with one colleague** (the person sitting next/closest to you) to code a portion of the same transcript, individually. Then you will compare your *codes* and check for consistencies or discrepancies between your two approaches.

## Task 1: Individual thematic coding

The first thing to do is to **quickly agree on which project you will be looking** at. It doesn't have to be the project that you decide to work on for the real assignment, *but it can be*. It will be useful for the coding exercise for you to be aware of the general aims of the research, so spend a few minutes to read through the project description.

Together with your activity partner, select one transcript at random from the folder containing the transcripts. Make sure to **download the data associated with your chosen project from Canvas rather than the project description pages**, because those datasets were simplified for ease of use.

Individually, at your desktops, perform a rough initial thematic coding of **the first three pages** of the transcript. This *coding* should look something like the example you have looked at in the first exercise, adding some comments on the Word document of the transcript. It does not need to be as detailed and rich in codes as that example.

Spend about 25 minutes on this task.

## Task 2: Compare your coding

After you have completed your initial coding individually, get together with your colleague and compare the thematic codes you have identified and discuss your strategy and findings in pairs.

Spend some 5-10 minutes on this task.

```{block , type = 'discussion-15'}
**Discussion**

Discuss with the seminar group:

- What were the themes that have emerged in your analyses?
- What is the overlap between the themes that different coders/pairs have identified?
- Are there any themes that only came up in your fragment?
- Imagine you all were analysts on the same large research project and the fragments you have just analysed was the complete data produced in the project. What would your collective approach be to developing *second-level* or *higher-level* thematic codes?

```

## Task 3: Start work on Assignment 2

`Start in class, continue outside class`

------------------------------------------------------------------------

Now that you have gained some practice with thematic coding, you can begin thinking about your analysis for Assignment 2. Have a look at the task and start selecting a project and a number of transcripts that you will focus your analysis on. Feel free to include the one you have just started coding in the previous exercise if you would like.

Rather than beginning any thematic coding just yet, a better approach for the assessment task would be to fist gain an overview perspective of your data (i.e. all the transcripts you have selected to include in your analysis). Gerson and Damaske (2020) call this step *initial immersion* and they advise to "start your analysis by reading the interview transcripts carefully and thoroughly" (p. 146). They then advise that you should select a software program for analysing qualitative data, but in your case the size of the data will not require this. The overhead of the learning curve would be too much for such a small project aimed at one assignment. You can instead follow the strategy we saw in the previous exercise and use standard word processing and tabulating software such as Word and Excel.

# Exercise 4: Think about qualitative analysis software options

`Outside class`

------------------------------------------------------------------------

Thinking ahead to your 3rd-year dissertation, it may be worth investing some time to get acquainted with some available software for qualitative analysis. The Canvas page lists some training options and software to get you started, so check them out. Qualitative data analysis suites are usually heavy and expensive proprietary programmes, but the University subscribes to some of them, such as NVivo.

If you are interested in some options for free, open source qualitative data analysis software that you may want to use in the future when you no longer have access to the subscription provided by the University, check out this interesting webinar presentation on the topic:

<iframe width="560" height="315" src="https://www.youtube.com/embed/9teZO-KVwqk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1">

</iframe>
