---
title: "SOC2069 Datasets"
format:
  html: 
    toc: true
    toc-location: left
    toc-title: "SOC2069 Datasets"
    embed-resources: false
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 5px
      gutter-width: 1.2rem
    # code-tools:
    #   source: https://link/to/exercise/sheet
css: "./../Materials/Labs/labcss.css"
---

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, include=FALSE}
library(tidyverse)
library(easystats)
library(DT)

DT:::DT2BSClass(c('compact', 'cell-border'))

```


These are real-life data from large-scale nationally representative surveys that include variables relating to (social) trust.
The datasets have been prepared for use in lab exercises and the assignment.
The original raw data files are freely available for research purposes from their respective data repositories, but they generally require registration before the data can be accessed.

The datasets listed on this page are slightly processed versions of the raw data to make them more easily usable by students.
Typically, variable types have been corrected and labels have been imported to `R`; the number of variables were reduced to include those of the greatest potential interest to sociology students.
Variable names and coding have *not* been altered, so that students can rely on the survey documentation (questionnaires, codebooks) to better understand the variables in the dataset.

The codebooks shown on this page describe the processed datasets.
The processed datasets can be downloaded by students from the module's institutional Canvas page for the purpose of coursework, but for all other research purposes students are asked to download the original raw data from the data repositories.
The `R` code available on this page can be run on the raw data to reproduce the processed datasets and can serve as a basis for further data wrangling.

Available datasets for download:

-   **World Values Survey, Wave 7**: `wvs7.rds` -- [**`Download`**](https://ncl.instructure.com/files/7506140/download?download_frd=1)
-   **European Values Study, 2017**: `evs2017.rds` -- [**`Download`**](https://ncl.instructure.com/files/7506137/download?download_frd=1)
-   **European Social Survey, Round 10, 2020**: `ess10.rds` -- [**`Download`**](https://ncl.instructure.com/files/7506136/download?download_frd=1)
-   **International Social Survey Programme, 2020**: `issp2020.rds` -- [**`Download`**](https://ncl.instructure.com/files/7506138/download?download_frd=1)
-   **British Social Attitudes Study, 2020**: `bsa2020.rds` -- [**`Download`**](https://ncl.instructure.com/files/7561699/download?download_frd=1)


::: dropdown
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Download data
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="https://ncl.instructure.com/files/7506140/download?download_frd=1">WVS 7</a></li>
    <li><a class="dropdown-item" href="https://ncl.instructure.com/files/7506137/download?download_frd=1">EVS 2017</a></li>
    <li><a class="dropdown-item" href="https://ncl.instructure.com/files/7506136/download?download_frd=1">ESS 10, 2020</a></li>
    <li><a class="dropdown-item" href="https://ncl.instructure.com/files/7506138/download?download_frd=1">ISSP, 2020</a></li>
    <li><a class="dropdown-item" href="https://ncl.instructure.com/files/7561699/download?download_frd=1">BSA, 2020</a></li>
  </ul>
:::



{{< include _wvs7_prep.qmd >}}

{{< include _evs2017_prep.qmd >}}

{{< include _ess10_prep.qmd >}}

{{< include _issp2020_prep.qmd >}}

{{< include _bsa2020_prep.qmd >}}
