---
title: Lecture notes
self-contained: true
bibliography: ../../../OneDrive - Newcastle University/LIBRARY/My Library.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/dependent/the-sociological-review.csl
format: pdf
---

## Introduction

Welcome to Researching Social Life 1. My name is Chris Moreh, your module leader.[^1]
You probably still remember me form last year's Knowing in Sociology, where in the second half of the module I introduced some of the methodological approaches that we will be looking at in a much more applied way here.
Before I briefly introduce the module and the semester, here's a reminder that you can contact me at my e-mail address and you can see me at the advertised office hours during the course of the module.


## Information

Even before we begin thinking about how to collect, process, analyse, interpret and present information as social scientists, it is useful to take a big step back and acknowledge, explicitly, some fundamental aspects of our human condition.
For better of worse, we are humans. That means that we have an innate capacity to perceive and process information through our senses, nervous system, brains. 
We are overall well equipped by nature, but not outstanding in any single aspect compared to other non-human animals; some other species have much better vision, or smell, or hearing, and so on.
So we are also limited by nature in our capacity to perceive and decode information. We often make mistakes, like when we misunderstand what is being said; song lyrics, for instance, are notorious source of confusion because they are often complicated by melody, rhythm, rhyme, and artistic freedom that doesn't require them to follow linguistic conventions of structure, grammar and meaning that we usual expect in our communicative use of language.

Our senses can also play tricks on us. (Just in case you haven't seen these images before: the lines in the picture at the top are actually straight, not sloping; and an elephant has four legs).
In everyday life, such errors in perception can be fun or just plain annoying. And we correct or adjust them in different ways, with more or less success. For instance, we may never be able to convince our brains that the lines in this picture are straight, no matter how much we stare at it. We're just not well equipped to process this visual information accurately. On the other hand, we know from other sources that an elephant has four legs - we might have seen one before, either in real life or depiction; or might have read about its anatomy in a book, etc. That's part of our common-sense knowledge. We are simply unwilling to let our brain convince us otherwise, and we would hardly update our common-sense knowledge and become convinced that an elephant in fact has five legs, no matter how long we stare at this picture.

Cognitive science has taught us a lot about the various fallacies that our brains are vulnerable to; and this natural disposition to malfunction is not necessarily something negative; in fact, it's an evolutionary device by which humans can make fast - if imperfect - decisions and act upon them automatically. Daniel Kahneman and his collaborators have done some illuminating experiments to demonstrate how our brains functions in a two-system mode. 95 % of the time we rely on this fast but error-prone information-processing system that makes social life possible and enjoyable; but analytical tasks require us to fight against these instincts and intuitions and instead make use of what Kahneman calls "System 2", reliant on rational thinking, slow, demanding a lot of effort and drawing conclusions that always admit the possibility of error.

We have also learnt a lot about the processing power and limitations of our brains by building artificial brains, computers, tools that outperform humans in many tasks, but by far not all. Research in artificial intelligence, psychology and philosophy has taught us about which are the areas that *can be* or are *worth* enhancing with computing technology, and which ones are best left to humans, either because our brains are still more powerful in those areas or just for ethical reasons.

Now this is all very interesting but we are most interested in learning how social scientists - sociologists - handle information about the social world. The point, nevertheless, is that sociologists are human, and the information they handle in their research is also produced and shaped by humans. So we should be very aware of the limitations of this information and of our abilities to correctly understand it and draw conclusions from it.

### Pic: Day in data

This is much more important today than it used to be back in the decades when the conventional methods of social research were devised, tested and described to students in methodology textbooks. In this module we focus mostly on such traditional methods as a foundation to understanding social research, but we should keep in mind that the mass and diversity of information available for sociological analysis today requires some new and innovative approaches.
Mass information presents social research with great opportunities but also poses serious challenges. In the broadest possible sense, the aim of social research is to 'tame' information that lives out there in the wilderness of the social world.

We often hear about *data*. Data are the bread and butter of empirical social research, and they come in many shapes and forms. But talking about data already involves a first act of 'taming'. In everyday life, we process a huge amount of information every day, every second, but we wouldn't think of it as 'data', mainly because we process it unconsciously. 'Data', however, implies some degree of consciousness and intentionality. For example, let's think of social media, a relatively recent but booming area of focus for data-driven social science. There are billions of words and sentences produced every day in the form of tweets, posts or messages; but these only become 'data' for a social scientist when she decides to look at this information with the intention of finding something out about the world. What underpins this intention is some specific interest or question. As we'll discuss later, formulating a research question is one of the first acts of 'taming' information, even when the information already exists somewhere and our stated intention to exploit it as *data* for our research question hasn't altered it in any way.

### Pic: Access to info vs. common sense

Taming information is a very important undertaking. We may think that having increasingly more access to raw, wild information is all it takes to understand the social world and improve our lot by acting on that information; but in fact what we need - and arguably still lack - is an efficient system for processing wild information. As social researchers, we need to balance the use of traditional and tested methods designed to explore information of a much more limited and structured nature, and developing new yet untested methods that are required to address new types and amounts of information. 

















[^1]: Module Canvas page is [https://ncl.instructure.com/courses/48074](https://ncl.instructure.com/courses/48074)