---
title: "Weekly materials"
css: labcss.css
---

```{r packages-data, include=FALSE} 

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
    tidyverse,
    knitr,
    kableExtra,
    lubridate,
    glue
    )
```


```{r build-table, echo=FALSE, results="asis"}

# week0 <- as_date("02-02-2023", format = '%d-%m-%Y') - 7

contents <- tibble(
  Week = c(paste("Week", 1:10)),
  # TW = c(22:29, 34:35),
  # Date = c(week0 + 7*1:8, week0 + 7*13:14),
#  Topic = rep("tbc", 10),
  Topic = c(paste0("var topic.w", 1:10)),
  # Info = c(paste0("/materials/notes/info_w", 1:10)),
  # Notes = c(paste0("/materials/notes/notes_w", 1:10)),
  Slides = c(paste0("https://github.com/CGMoreh/SOC2069/raw/main/Materials/Slides/Week_", 1:10)),
  Labs = c(paste0("/labs/worksheet_", 1:10)),
  # Handouts = c(paste0("/materials/handouts/sheet_w", 1:10)),
  )

# write_csv(contents, "files/contents.csv") 

contents <- contents |>
  mutate(
        # Date = format(as_date(Date), "%d %B"),
         # Info = paste0("[{{< fa solid circle-info >}}]", glue('({Info}.qmd)')),
         # Notes = paste0("[{{< fa solid book-open >}}]", glue('({Notes}.qmd)')),
         Slides = paste0("[{{< fa solid person-chalkboard >}}]", glue('({Slides}.pptx)')),
         Labs = paste0("[", "Lab", 1:10, "]", glue('({Labs}.qmd)')),
         # Handouts = paste0("[{{< fa solid sheet-plastic >}}]", glue('({Handouts}.qmd)')),
         Topic = paste("{{< ", Topic, " >}}"))


contents[2, 4] <- paste(paste0("[", "Lab2a", "]", glue('(Labs/Worksheet_2a.qmd)')),
                        paste0("[", "Lab2b", "]", glue('(Labs/Worksheet_2b.qmd)')))


tbl <- contents |>
  kbl(escap = FALSE, align = "llll", table.attr = 'class="schedule-table"') |>
  kable_styling() |>
  column_spec(1, width = "5%") |>  
  column_spec(2, width = "25%") |>  
  column_spec(3, width = "10%") |>  
  column_spec(4, width = "10%")

  cat(tbl)

```

